### ISSUE TITLE
无法收到回复

### ISSUE THREAD

**Issue by damingsi** [SnapdragonLee/ChatGPT-weBot#1]
无法收到回复 log里面可以看到它发送了

**Comment by damingsi** [comment]
全部都是心跳的log 给微信发信息之后会有一个send的log 然后就没有了

**Comment by SnapdragonLee** [comment]
是的 revchatgpt我已经发起了issue，我推测是OpenAIAuth的问题，暂时我也没时间排查问题

**Comment by hezzze** [comment]
我这边是一直显示 access token is missing 

然后好像是OpenAI宕机了 ...

https://status.openai.com/#

**Comment by SnapdragonLee** [comment]
项目基于的是逆向API，来自于acheong08/ChatGPT，昨天早上我提交了第一个issue，作者已经确认 OpenAIAuth出现了bug，详情可以查看 https://github.com/acheong08/ChatGPT/issues/845

**Comment by carols1989** [comment]
> 

删除掉rev_config.json中的access_token或者调整代码中的判断逻辑之后就能正常运行了，修改之前的代码不会去执行hearders的更新

**Comment by SnapdragonLee** [comment]
> > 
> 
> 删除掉rev_config.json中的access_token或者调整代码中的判断逻辑之后就能正常运行了，修改之前的代码不会去执行hearders的更新

正解，已经更新
