### ISSUE TITLE
免费提供一个免费开源微信框架，千寻框架 基本hook可以用来接入chatgpt

### ISSUE THREAD

**Issue by joe12801** [SnapdragonLee/ChatGPT-weBot#14]
开源仓库/下载地址（求Star）：https://gitee.com/ai-chen-qi/pc-v-hook-http-api
开发文档：�https://www.apifox.cn/apidoc/shared-af49a169-8b5c-4137-a5ea-723a10e8e794/doc-1046131 密码 vHCAG7IM

**Comment by SnapdragonLee** [comment]
我有看到千寻框架，如果大家非常迫切需要这样的需求、且我时间充裕，可以尝试使用这个框架。
短时间内没有这个打算
