### ISSUE TITLE
这个框架是单线程的吗，也就是只能一个一个问题问吗？

### ISSUE THREAD

**Issue by SHEN2BAIYI** [SnapdragonLee/ChatGPT-weBot#15]
我在使用机器人的时候，如果一个问题比较难，机器人会花两分钟来回答这个问题，那么这个主程序就会卡住两分钟，期间不会对任何事情产生响应，也没有 heart beat。并且当两个人同时问问题的时候，它会忽略掉第二个问题。

**Comment by SnapdragonLee** [comment]
不会忽略问题，会很慢，本身chatgpt也只是支持一个线程提问的

**Comment by SHEN2BAIYI** [comment]
我在群聊里面使用的时候，如果两个人很临近的提出问题，他就会忽略掉第二个的信息。这个有可能是 chatGPT 反向工程那部分的问题。

**Comment by SnapdragonLee** [comment]
> 我在群聊里面使用的时候，如果两个人很临近的提出问题，他就会忽略掉第二个的信息。这个有可能是 chatGPT 反向工程那部分的问题。

听了你的描述 我感觉这个问题很大，我需要亲自指导到底发生了什么

**Comment by SHEN2BAIYI** [comment]
> > 我在群聊里面使用的时候，如果两个人很临近的提出问题，他就会忽略掉第二个的信息。这个有可能是 chatGPT 反向工程那部分的问题。
> 
> 听了你的描述 我感觉这个问题很大，我需要亲自知道到底发生了什么

我是使用两个wx进行测试，在群里面同时发出问询指令，机器人会显示收到两条消息，但是只会回复第一个人。

**Comment by oursy** [comment]
维护一个接收消息队列结合 Semaphore 实现

**Comment by SnapdragonLee** [comment]
> 

嗯，只能接入模型去做了，短期内可能不会花太多时间搞这个，我会仔细权衡这个和多线程回复的关系

**Comment by cappiewu** [comment]
> > 
> 嗯，只能接入模型去做了，短期内可能不会花太多时间搞这个，我会仔细权衡这个和多线程回复的关系

ChatGPT的反馈比较慢，与其考虑多线程，不如用一个队列去保存用户消息，队列有限额，例如保存3个消息，满3个后再有人提问就直接回复“我还在思考XXX、XXX的问题”，这样可能会比较好

**Comment by SnapdragonLee** [comment]
> > > 
> 
> > 嗯，只能接入模型去做了，短期内可能不会花太多时间搞这个，我会仔细权衡这个和多线程回复的关系
> 
> 
> 
> ChatGPT的反馈比较慢，与其考虑多线程，不如用一个队列去保存用户消息，队列有限额，例如保存3个消息，满3个后再有人提问就直接回复“我还在思考XXX、XXX的问题”，这样可能会比较好

是的，这也是我在做的，如果有多个账号登录，可以多个线程生产消费

**Comment by SnapdragonLee** [comment]
已经更新了多线程队列，但多账号因为我没有所以暂时没法测试，这两天我会尽快测，已经记录在更新计划了
