### ISSUE TITLE
逆向工程API已经G了，按道理只能等待

### ISSUE THREAD

**Issue by SnapdragonLee** [SnapdragonLee/ChatGPT-weBot#17]
> 从CHATGPT返回错误代码有1020，我用chatgpt问了一下怎么回事：
> chatgpt的Error code: 1020
> 如果您在使用 OpenAI 的 ChatGPT 模型时遇到 Error code 1020，那么可能是因为您的请 > 求不符合 API 的规范，或者出现了其他问题导致 API 调用失败。
> 建议您检查您的 API 请求，确保其符合 API 的规范。您还可以联系 OpenAI 的技术支持团> 队，以获得帮助。他们可以帮助您诊断和解决问题，以确保您的 API 调用正常工作。

我会观察作者 acheong08 的修改，修改好了我会尽快更改库里面与chatgpt连接的部分，现在先耐心等待一下吧

如果有非常紧急的任务，只能使用 chatgpt 网页版。

_Originally posted by @LeonLee888 in https://github.com/SnapdragonLee/ChatGPT-weBot/issues/6#issuecomment-1445546187_

**Comment by LeonLee888** [comment]
我还调试了一早上，还以为是我账号PRO的问题，特别注册了个非PRO版本的~ 大神多多努力吧

**Comment by SnapdragonLee** [comment]
> 我还调试了一早上，还以为是我账号PRO的问题，特别注册了个非PRO版本的~ 大神多多努力吧

其实也就是从9点多开始的这个问题，之前一直都没有的，以后也会是这样，每当chatgpt要更新之前，都会有这么一段时间出问题

**Comment by SnapdragonLee** [comment]
> 

正确的，耐心等下吧

**Comment by SnapdragonLee** [comment]
> 正常，道高一尺魔高一丈~ 黑科技就是一直迭代~ 期待官方的正式3.5API接口出来

正确的，耐心等下吧

**Comment by tommyxps** [comment]
遇到同样问题，加油！

**Comment by SnapdragonLee** [comment]
[[Bug]: Access Denied Error #922](https://github.com/acheong08/ChatGPT/issues/922)
[[Bug]: revChatGPT.V1.Error. #923](https://github.com/acheong08/ChatGPT/issues/923)

**Comment by SnapdragonLee** [comment]
已经解决
