### ISSUE TITLE
请求增加群消息总结要点功能

### ISSUE THREAD

**Issue by lzcwy** [SnapdragonLee/ChatGPT-weBot#19]
详细描述如下：
记录群成员发送过的信息，发送关键字命令之后，将本群成员发送过的消息喂给chatgpt总结聊天要点，chatgpt总结完聊天要点之后回传给客户端，然后清空本次记录的聊天信息，下一次再发送关键字命令时，总结的是新记录的聊天要点

示例如下：
![image](https://user-images.githubusercontent.com/49913480/221518725-ba04f5f0-a08f-456c-bc4f-8dcaec57accb.png)

**Comment by SnapdragonLee** [comment]
大致明白了，但chatgpt总结时有字数限制，这是需要考虑的一个问题
另外，喂给chatgpt时是否需要明确昵称等其他信息

**Comment by SnapdragonLee** [comment]
不建议使用这个功能，这个功能对于现有的程序体系负载较大，联系的模块也要比现有功能多很多，因此暂时不考虑，谢谢理解
