### ISSUE TITLE
关于响应关键词的问题

### ISSUE THREAD

**Issue by tiexo** [SnapdragonLee/ChatGPT-weBot#20]
响应关键词有什么规则吗？

-c

前面一定要加 “-”么，能不能换成其他符号
或者直接用一个词语代替，比如 “机器人”

也就是：机器人 你好啊

还有一个问题，用电脑版微信输入“-c”识别不了，用手机又可以

**Comment by SnapdragonLee** [comment]
> 响应关键词有什么规则吗？
> 
> 
> 
> -c
> 
> 
> 
> 前面一定要加 “-”么，能不能换成其他符号
> 
> 或者直接用一个词语代替，比如 “机器人”
> 
> 
> 
> 也就是：机器人 你好啊
> 
> 
> 
> 还有一个问题，用电脑版微信输入“-c”识别不了，用手机又可以

注意看readme，你需要修改config.json来自定义关键字，你说的情形是可以的

关于第二个问题，实际上就是这样的，你说的现象是正确的

**Comment by tiexo** [comment]
> > 响应关键词有什么规则吗？
> > -c
> > 前面一定要加 “-”么，能不能换成其他符号
> > 或者直接用一个词语代替，比如 “机器人”
> > 也就是：机器人 你好啊
> > 还有一个问题，用电脑版微信输入“-c”识别不了，用手机又可以
> 
> 注意看readme，你需要修改config.json来自定义关键字，你说的情形是可以的
> 
> 关于第二个问题，实际上就是这样的，你说的现象是正确的

确实实现了。
还有一个问题请教，我尝试用bat实现微信双开，好像没有效果，win11系统。
搜了半天，也没搜到同时安装两个不同版本微信的方法，即便选择不同的目录，也会被替代掉。

**Comment by tiexo** [comment]
> > 响应关键词有什么规则吗？
> > -c
> > 前面一定要加 “-”么，能不能换成其他符号
> > 或者直接用一个词语代替，比如 “机器人”
> > 也就是：机器人 你好啊
> > 还有一个问题，用电脑版微信输入“-c”识别不了，用手机又可以
> 
> 注意看readme，你需要修改config.json来自定义关键字，你说的情形是可以的
> 
> 关于第二个问题，实际上就是这样的，你说的现象是正确的

确实实现了。
还有一个问题请教，我尝试用bat实现微信双开，好像没有效果，win11系统。
搜了半天，也没搜到同时安装两个不同版本微信的方法，即便选择不同的目录，也会被替代掉。

**Comment by SnapdragonLee** [comment]
> > > 响应关键词有什么规则吗？
> > > -c
> > > 前面一定要加 “-”么，能不能换成其他符号
> > > 或者直接用一个词语代替，比如 “机器人”
> > > 也就是：机器人 你好啊
> > > 还有一个问题，用电脑版微信输入“-c”识别不了，用手机又可以
> > 
> > 
> > 注意看readme，你需要修改config.json来自定义关键字，你说的情形是可以的
> > 关于第二个问题，实际上就是这样的，你说的现象是正确的
> 
> 确实实现了。 还有一个问题请教，我尝试用bat实现微信双开，好像没有效果，win11系统。 搜了半天，也没搜到同时安装两个不同版本微信的方法，即便选择不同的目录，也会被替代掉。

双开脚本可以用，我这里是win10 x64系统，亲测没有任何问题
注意，我在#的注释后面写了在双引号内填写不同版本微信的安装目录，如果你看到没有效果，可以在脚本的下面空白行开头写一句 pause，保存运行后可以截图贴在这里

**Comment by SnapdragonLee** [comment]
已经更新0.99-dev，目前这个问题应该已经被解决
