### ISSUE TITLE
有人在群里使用相同的额头像和名称，冒充bot，可以添加一个功能验证自己身份么

### ISSUE THREAD

**Issue by tommyxps** [SnapdragonLee/ChatGPT-weBot#22]
如题

比如在回答的时候加入特殊的验证形式，证明现在回答的是bot，不是伪装者

**Comment by SnapdragonLee** [comment]
> 如题
> 
> 
> 
> 比如在回答的时候加入特殊的验证形式，证明现在回答的是bot，不是伪装者

很遗憾，群聊现在因为dll有bug，所以暂时没办法修，我会尽快联系作者修复

**Comment by tommyxps** [comment]
好的好的 没事 感谢回答

**Comment by SnapdragonLee** [comment]
最新的SDK可以做到验证了，但主体部分还没有完成
群聊也支持@人了，所以这个群聊的bug基本可以无视了
