### ISSUE TITLE
今天是被墙了么？

### ISSUE THREAD

**Issue by gc528262067** [SnapdragonLee/ChatGPT-weBot#23]

**Comment by gc528262067** [comment]
error from callback <function on_open at 0x03AD3030>: HTTPSConnectionPool(host='explorer.api.openai.com', port=443): Max retries exceeded with url: /api/auth/session (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x03AF2050>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没 有反应，连接尝试失败。',))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\websocket\_app.py", line 393, in _callback
    callback(self, *args)
  File "C:\Users\Administrator\Downloads\ChatGPT-weBot-master\client\wxclient.py", line 367, in on_open
    parent_id=None,
  File "C:\Users\Administrator\Downloads\ChatGPT-weBot-master\revChat\revChatGPT.py", line 68, in __init__
    self.__check_credentials()
  File "C:\Users\Administrator\Downloads\ChatGPT-weBot-master\revChat\revChatGPT.py", line 81, in __check_credentials
    self.login()
  File "C:\Users\Administrator\Downloads\ChatGPT-weBot-master\revChat\revChatGPT.py", line 111, in login
    auth.get_access_token()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\OpenAIAuth.py", line 315, in get_access_token
    "https://explorer.api.openai.com/api/auth/session",
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
    
    
    不开代理就报这个错误 开了代理报SSL错误

**Comment by SnapdragonLee** [comment]
我这里显示一切正常

**Comment by ymeimei** [comment]
> 来自回调的错误 <function on_open at 0x03AD3030>: HTTPSConnectionPool(host='explorer.api.openai.com', port=443): 最大重试次数超过 url: /api/auth/session （由 NewConnectionError('<urllib3. connection.HTTPSConnection object at 0x03AF2050>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确回答或连接的主机没有反应，连接尝试失败".\',') C Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\websocket_app.py"，第 393 行，在 _callback callback(self, *args) File "C:\Users\Administrator\Downloads\ ChatGPT-weBot-master\client\wxclient.py”，第 367 行，on_open parent_id=None， 文件“C:\Users\Administrator\Downloads\ChatGPT-weBot-master\revChat\revChatGPT.py”，第 68 行，在**初始化** self.__check_credentials() 文件“C:\Users\Administrator\Downloads\ChatGPT-weBot-master\revChat\revChatGPT.py”，第 81 行，在 __check_credentials self.login () 文件“C:\Users\Administrator\Downloads\ChatGPT-weBot-master \revChat\revChatGPT.py”，第111行，登录 auth.get_access_token() 文件“C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\OpenAIAuth.py”，第 315 行，在获取访问令牌 “ https://explorer.api.openai.com/api/auth/session ”， 文件“C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site- packages\requests\sessions.py", line 542, in get return self.request('GET', url, **kwargs) 文件“C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py”，第 529 行，请求 resp = self.send(prep, ** send_kwargs ) 文件“C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py”，第 645 行，在 send r = adapter.send(request, ** kwargs) 文件“C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\adapters.py”，第 519 行，在发送中引发 ConnectionError(e, request=request )
> 
> ```
> 不开代理就报这个错误 开了代理报SSL错误
> ```

我和你一样的问题，昨晚出现的，然后关了等了一晚上早上还是连不上去

**Comment by SnapdragonLee** [comment]
> 

我感觉是不是因为限流了，建议可以改一下连接的地址换成其他人的代理服务器上去，比如可以试试这个能不能上去：
`revChatGPT.py` 中的 12、13行可以选择其中一个试试看

**Comment by tommyxps** [comment]
限流的提示是 proxy server rate limited 么？

**Comment by gc528262067** [comment]
> 我这里显示一切正常

哦吼  你用的python版本是哪个啊  我用的3.6

**Comment by SnapdragonLee** [comment]
> > 我这里显示一切正常
> 
> 哦吼 你用的python版本是哪个啊 我用的3.6

版本不是问题吧，我这个应该是python3都能跑的hhh，我用的3.8-3.10都可以跑

**Comment by gc528262067** [comment]
> > 
> 
> 我感觉是不是因为限流了，建议可以改一下连接的地址换成其他人的代理服务器上去，比如可以试试这个能不能上去： `revChatGPT.py` 中的 12、13行可以选择其中一个试试看

晚上回去试试去

**Comment by gc528262067** [comment]
> > > 我这里显示一切正常
> > 
> > 
> > 哦吼 你用的python版本是哪个啊 我用的3.6
> 
> 版本不是问题吧，我这个应该是python3都能跑的hhh，我用的3.8-3.10都可以跑

我觉得也不是版本的问题。。。

**Comment by tommyxps** [comment]
> > 限流的提示是 proxy server rate limited 么？
> 
> 
> 
> 不太清楚，我没有触发过这种错误，帮不到你捏

我重新启动了下就好了 
重启是因为遇到了一个更奇怪的issue： 群里有人给他的指令是对他的问题五分钟禁言 结果5min之后这人直接被忽视 他所有问题后台都显示error 其他人问题都是正常回答 

我重启后好了 奇怪🤔

**Comment by SnapdragonLee** [comment]
> 

？？年轻人会玩奥，我没这么玩过哈哈哈哈，这是什么奇怪的情况

**Comment by zhaojinfeng5** [comment]
> 

我这边依旧报这个错，开不开代理都不行，重启也无效
error from callback <function on_open at 0x00000235D6219B88>: HTTPSConnectionPool(host='explorer.api.openai.com', port=443): Max retries exceeded with url: /api/auth/session (Caused by NewConnectionError('<urllib3.connection.HTTPSConne
ction object at 0x00000235D62460C8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
  File "D:\python_projec\ChatGPT-weBot\venv\lib\site-packages\websocket\_app.py", line 393, in _callback
    callback(self, *args)

**Comment by SnapdragonLee** [comment]
> > 
> 
> 我这边依旧报这个错，开不开代理都不行，重启也无效 error from callback <function on_open at 0x00000235D6219B88>: HTTPSConnectionPool(host='explorer.api.openai.com', port=443): Max retries exceeded with url: /api/auth/session (Caused by NewConnectionError('<urllib3.connection.HTTPSConne ction object at 0x00000235D62460C8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。')) File "D:\python_projec\ChatGPT-weBot\venv\lib\site-packages\websocket_app.py", line 393, in _callback callback(self, *args)

我没有遇到过这个情况，唯一能建议的就是如果网页端可以上去的话，本地一定一定可以上去，唯一的可能就是ip所在的请求过多，或者短时间产生非常多的登录请求等。建议可以换换ip

**Comment by zhaojinfeng5** [comment]
> > > 
> > 
> > 
> > 我这边依旧报这个错，开不开代理都不行，重启也无效 error from callback <function on_open at 0x00000235D6219B88>: HTTPSConnectionPool(host='explorer.api.openai.com', port=443): Max retries exceeded with url: /api/auth/session (Caused by NewConnectionError('<urllib3.connection.HTTPSConne ction object at 0x00000235D62460C8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。')) File "D:\python_projec\ChatGPT-weBot\venv\lib\site-packages\websocket_app.py", line 393, in _callback callback(self, *args)
> 
> 我没有遇到过这个情况，唯一能建议的就是如果网页端可以上去的话，本地一定一定可以上去。唯一的可能就是ip所在的请求过多，或者短时间产生非常多的登录请求等。建议可以换换ip

请问你这里说的网页端可以上去是指哪个网址能上去，https://apps.openai.com/吗

**Comment by SnapdragonLee** [comment]
> > > > 
> > > 
> > > 
> > > 我这边依旧报这个错，开不开代理都不行，重启也无效 error from callback <function on_open at 0x00000235D6219B88>: HTTPSConnectionPool(host='explorer.api.openai.com', port=443): Max retries exceeded with url: /api/auth/session (Caused by NewConnectionError('<urllib3.connection.HTTPSConne ction object at 0x00000235D62460C8>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。')) File "D:\python_projec\ChatGPT-weBot\venv\lib\site-packages\websocket_app.py", line 393, in _callback callback(self, *args)
> > 
> > 
> > 我没有遇到过这个情况，唯一能建议的就是如果网页端可以上去的话，本地一定一定可以上去。唯一的可能就是ip所在的请求过多，或者短时间产生非常多的登录请求等。建议可以换换ip
> 
> 请问你这里说的网页端可以上去是指哪个网址能上去，[https://apps.openai.com/吗](https://apps.openai.com/%E5%90%97)

不不不，就是 chat.openai.com

**Comment by zhaojinfeng5** [comment]
> 

开代理能登，然后我把session token拷贝进来了，跑python的时候要开代理吗，虽然我试过开了也报这个错

**Comment by SnapdragonLee** [comment]
> 

不需要开代理，但一个ip不允许短时间多次频繁请求

**Comment by zhaojinfeng5** [comment]
> > 
> 
> 不需要开代理，但一个ip不允许短时间多次频繁请求

可是我一次都没有成功过.. 有什么其他方式可以尝试吗，换ip也不行。我用的DLLinjector_V1.0.3注入，这个没问题吧？

**Comment by SnapdragonLee** [comment]
> > > 
> > 
> > 
> > 不需要开代理，但一个ip不允许短时间多次频繁请求
> 
> 可是我一次都没有成功过.. 有什么其他方式可以尝试吗，换ip也不行。我用的DLLinjector_V1.0.3注入，这个没问题吧？

不是注入的问题，你是chatgpt没有登陆上去的问题，你可以试试代理服务器：revChatGPT.py 中的 12、13行可以选择其中一个试试看

**Comment by zhaojinfeng5** [comment]
> 你是chatgpt没有登陆上去的问题
我试了切换12/13行，也不work，话说 rev_config.json 里我只设置了session_token，因为我用的gmail邮箱，只需要且只能设置session_token对吗？

**Comment by gc528262067** [comment]
> Reference in

我ping了下哪两个域名 全部超时了。。。

**Comment by zhaojinfeng5** [comment]
> > Reference in
> 
> 我ping了下哪两个域名 全部超时了。。。

12行那个我倒是能ping通

**Comment by ymeimei** [comment]
确实换了ip也不行，代理服务器也报错，奇怪了

**Comment by gc528262067** [comment]
> 确实换了ip也不行，代理服务器也报错，奇怪了

开会。。这两个被ban了吧。。

**Comment by zeng9820** [comment]
![image](https://user-images.githubusercontent.com/64820318/222652382-36ddd91f-2c18-48b1-98eb-f0cf3a7196c7.png)
我也ping不通

**Comment by gc528262067** [comment]
> > > Reference in
> > 
> > 
> > 我ping了下哪两个域名 全部超时了。。。
> 
> 12行那个我倒是能ping通

我偶尔能ping通。就是连不上 奇了怪了

**Comment by zhaojinfeng5** [comment]
报错的是这个地址 https://explorer.api.openai.com/api/auth/session 访问不了

> ![image](https://user-images.githubusercontent.com/64820318/222652382-36ddd91f-2c18-48b1-98eb-f0cf3a7196c7.png) 我也ping不通

把协议头去掉

**Comment by zhaojinfeng5** [comment]
> > > > Reference in
> > > 
> > > 
> > > 我ping了下哪两个域名 全部超时了。。。
> > 
> > 
> > 12行那个我倒是能ping通
> 
> 我偶尔能ping通。就是连不上 奇了怪了

看报错是 https://explorer.api.openai.com/api/auth/session 访问不了

**Comment by zeng9820** [comment]
> 报错的是这个地址 https://explorer.api.openai.com/api/auth/session 访问不了
> 
> > ![image](https://user-images.githubusercontent.com/64820318/222652382-36ddd91f-2c18-48b1-98eb-f0cf3a7196c7.png) 我也ping不通
> 
> 把协议头去掉

我也是chatgpt.duti.tech能ping通，另外一个超时

**Comment by SnapdragonLee** [comment]
很奇怪，我这里一直都是通的，且我个人透露一下我网络环境就在北京。或许你们可能需要试试挂一下全局代理试试

**Comment by zhaojinfeng5** [comment]
> 很奇怪，我这里一直都是通的，且我个人透露一下我网络环境就在北京。或许你们可能需要试试挂一下全局代理试试
> 
> 顺便我放一张图，证明一下： ![image](https://user-images.githubusercontent.com/61799448/222653662-2e339ed6-c07e-4d04-b39f-46fce09c383c.png)

试了全局代理，也是一样的报错，还没有成功过..

**Comment by zhaojinfeng5** [comment]
> 很奇怪，我这里一直都是通的，且我个人透露一下我网络环境就在北京。或许你们可能需要试试挂一下全局代理试试
> 
> 顺便我放一张图，证明一下： ![image](https://user-images.githubusercontent.com/61799448/222653662-2e339ed6-c07e-4d04-b39f-46fce09c383c.png)

你是用的session token还是邮箱密码

**Comment by SnapdragonLee** [comment]
> 

session_token， 邮箱密码貌似很难成功，且我没有这种账号

**Comment by zhaojinfeng5** [comment]
> > 
> 
> session_token， 邮箱密码貌似很难成功，且我没有这种账号

那真的太奇怪了，尝试了多次还是不行

**Comment by SnapdragonLee** [comment]
> > > 
> > 
> > 
> > session_token， 邮箱密码貌似很难成功，且我没有这种账号
> 
> 那真的太奇怪了，尝试了多次还是不行

我在猜想，你的全局代理是走虚拟网卡接管流量的嘛，是不是问题可能发生在这里，但是我试了一下裸连我也能上去

**Comment by joe12801** [comment]
没有问题

**Comment by zhaojinfeng5** [comment]
> > > > 
> > > 
> > > 
> > > session_token， 邮箱密码貌似很难成功，且我没有这种账号
> > 
> > 
> > 那真的太奇怪了，尝试了多次还是不行
> 
> 我在猜想，你的全局代理是走虚拟网卡接管流量的嘛，是不是问题可能发生在这里，但是我试了一下裸连我也能上去

我换了个全局代理，现在换了报错：error from callback <function on_message at 0x0000027997B18C18>: HTTPSConnectionPool(host='explorer.api.openai.com', port=443): Max retries exceeded with url: /api/auth/session (Caused by ProxyError('Cannot connect to proxy.', OSError(
0, 'Error')))

**Comment by zhaojinfeng5** [comment]
> 

确实，开了代理报https错误了

**Comment by zhaojinfeng5** [comment]
> > > > 
> > > 
> > > 
> > > session_token， 邮箱密码貌似很难成功，且我没有这种账号
> > 
> > 
> > 那真的太奇怪了，尝试了多次还是不行
> 
> 我在猜想，你的全局代理是走虚拟网卡接管流量的嘛，是不是问题可能发生在这里，但是我试了一下裸连我也能上去

显示连上gpt了！不过又报了这个错：
ask: 你是谁
{"detail":"Hmm...something seems to have gone wrong. Maybe try me again in a little bit."}
error from callback <function on_message at 0x0000026B2D563DC8>: 
  File "D:\python_projec\ChatGPT-weBot\venv\lib\site-packages\websocket\_app.py", line 393, in _callback

**Comment by ymeimei** [comment]
> > > > > 
> > > > 
> > > > 
> > > > session_token， 邮箱密码貌似很难成功，且我没有这种账号
> > > 
> > > 
> > > 那真的太奇怪了，尝试了多次还是不行
> > 
> > 
> > 我在猜想，你的全局代理是走虚拟网卡接管流量的嘛，是不是问题可能发生在这里，但是我试了一下裸连我也能上去
> 
> 显示连上gpt了！不过又报了这个错： ask: 你是谁 {"detail":"Hmm...something seems to have gone wrong. Maybe try me again in a little bit."} error from callback <function on_message at 0x0000026B2D563DC8>: File "D:\python_projec\ChatGPT-weBot\venv\lib\site-packages\websocket_app.py", line 393, in _callback

你怎么连上的，全局代理吗

**Comment by zhaojinfeng5** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > session_token， 邮箱密码貌似很难成功，且我没有这种账号
> > > > 
> > > > 
> > > > 那真的太奇怪了，尝试了多次还是不行
> > > 
> > > 
> > > 我在猜想，你的全局代理是走虚拟网卡接管流量的嘛，是不是问题可能发生在这里，但是我试了一下裸连我也能上去
> > 
> > 
> > 显示连上gpt了！不过又报了这个错： ask: 你是谁 {"detail":"Hmm...something seems to have gone wrong. Maybe try me again in a little bit."} error from callback <function on_message at 0x0000026B2D563DC8>: File "D:\python_projec\ChatGPT-weBot\venv\lib\site-packages\websocket_app.py", line 393, in _callback
> 
> 你怎么连上的，全局代理吗

是的，全局代理

**Comment by ymeimei** [comment]
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > session_token， 邮箱密码貌似很难成功，且我没有这种账号
> > > > > 
> > > > > 
> > > > > 那真的太奇怪了，尝试了多次还是不行
> > > > 
> > > > 
> > > > 我在猜想，你的全局代理是走虚拟网卡接管流量的嘛，是不是问题可能发生在这里，但是我试了一下裸连我也能上去
> > > 
> > > 
> > > 显示连上gpt了！不过又报了这个错： ask: 你是谁 {"detail":"Hmm...something seems to have gone wrong. Maybe try me again in a little bit."} error from callback <function on_message at 0x0000026B2D563DC8>: File "D:\python_projec\ChatGPT-weBot\venv\lib\site-packages\websocket_app.py", line 393, in _callback
> > 
> > 
> > 你怎么连上的，全局代理吗
> 
> 是的，全局代理

可以推一下软件吗，我的开了全局之后依然报错==

**Comment by zhaojinfeng5** [comment]
> > > > > > > > 
> > > > > > > 
> > > > > > > 
> > > > > > > session_token， 邮箱密码貌似很难成功，且我没有这种账号
> > > > > > 
> > > > > > 
> > > > > > 那真的太奇怪了，尝试了多次还是不行
> > > > > 
> > > > > 
> > > > > 我在猜想，你的全局代理是走虚拟网卡接管流量的嘛，是不是问题可能发生在这里，但是我试了一下裸连我也能上去
> > > > 
> > > > 
> > > > 显示连上gpt了！不过又报了这个错： ask: 你是谁 {"detail":"Hmm...something seems to have gone wrong. Maybe try me again in a little bit."} error from callback <function on_message at 0x0000026B2D563DC8>: File "D:\python_projec\ChatGPT-weBot\venv\lib\site-packages\websocket_app.py", line 393, in _callback
> > > 
> > > 
> > > 你怎么连上的，全局代理吗
> > 
> > 
> > 是的，全局代理
> 
> 可以推一下软件吗，我的开了全局之后依然报错==

什么软件

**Comment by SnapdragonLee** [comment]
该帖子为代理问题，请移步到代理问题issue专区 #11
