### ISSUE TITLE
可以增加多账号的功能吗

### ISSUE THREAD

**Issue by joe12801** [SnapdragonLee/ChatGPT-weBot#24]
可以增加多账号的功能吗，因为免费的每个小时只能请求50次，所以请求增加多账号模式

**Comment by SnapdragonLee** [comment]
正在着手做这个事情了，其实事实上已经基本写完了，在做其余的工作

**Comment by SnapdragonLee** [comment]
回复您的issue，现阶段异步回复消息队列已经完成，但没有多余账号做多账号测试，我会尽快完成这部分

**Comment by SnapdragonLee** [comment]
#40
