### ISSUE TITLE
DLL注入器和.dll文件如何获取？

### ISSUE THREAD

**Issue by wxy116586** [SnapdragonLee/ChatGPT-weBot#25]

**Comment by Delppine1024** [comment]
在releases中

**Comment by wxy116586** [comment]
感谢你的回复，很棒的作品！我已经成功使用了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SnapdragonLee/ChatGPT-weBot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月4日(星期六) 中午11:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SnapdragonLee/ChatGPT-weBot] DLL注入器和.dll文件如何获取？ (Issue #25)





 
在releases中

**Comment by wxy116586** [comment]
麻烦请教一下，我想在服务器上运行您的程序，我应该怎么在linux系统中注入dll？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SnapdragonLee/ChatGPT-weBot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月4日(星期六) 中午11:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SnapdragonLee/ChatGPT-weBot] DLL注入器和.dll文件如何获取？ (Issue #25)





 
在releases中

**Comment by SnapdragonLee** [comment]
> 麻烦请教一下，我想在服务器上运行您的程序，我应该怎么在linux系统中注入dll？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "SnapdragonLee/ChatGPT-weBot" ***@***.***&gt;; 发送时间:&nbsp;2023年3月4日(星期六) 中午11:09 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [SnapdragonLee/ChatGPT-weBot] DLL注入器和.dll文件如何获取？ (Issue #25) 在releases中 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

这部分我有听说docker-wine的注入方式，但是据反馈不是很稳定，后面我也会尝试这种方式，但是目前我会更新多线程和简单的txt2img功能

**Comment by wxy116586** [comment]
好的，感谢您的回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SnapdragonLee/ChatGPT-weBot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月4日(星期六) 下午2:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SnapdragonLee/ChatGPT-weBot] DLL注入器和.dll文件如何获取？ (Issue #25)





  
麻烦请教一下，我想在服务器上运行您的程序，我应该怎么在linux系统中注入dll？
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "SnapdragonLee/ChatGPT-weBot" @.&gt;; 发送时间:&nbsp;2023年3月4日(星期六) 中午11:09 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [SnapdragonLee/ChatGPT-weBot] DLL注入器和.dll文件如何获取？ (Issue #25) 在releases中 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
这部分我有听说docker-wine的注入方式，但是据反馈不是很稳定，后面我也会尝试这种方式，但是目前我会更新多线程和简单的txt2img功能

**Comment by SnapdragonLee** [comment]
已经记录在小本上了，后续有进展我会自己发issue

**Comment by wxy116586** [comment]
&nbsp;
您好 想问问一直卡在这个页面是什么原因导致的？我换了新设备，不过配置和之前旧设备的配置一致，开了网络代理，旧设备是可以成功运行的，新设备跑不起来了，和python版本有关吗


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SnapdragonLee/ChatGPT-weBot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月4日(星期六) 晚上9:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SnapdragonLee/ChatGPT-weBot] DLL注入器和.dll文件如何获取？ (Issue #25)





 
已经记录在小本上了，后续有进展我会自己发issue

**Comment by wxy116586** [comment]
好的，谢谢回复，有什么是我能帮上忙的吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SnapdragonLee/ChatGPT-weBot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月10日(星期五) 中午1:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SnapdragonLee/ChatGPT-weBot] DLL注入器和.dll文件如何获取？ (Issue #25)





 
@wxy116586 目前这个版本不行，我会更新API版本
