### ISSUE TITLE
可否增加一点小提示

### ISSUE THREAD

**Issue by skyyaman** [SnapdragonLee/ChatGPT-weBot#27]
有时候回复等待时间较长，建议可以在一定秒数后输出“请耐心等待”之类的提示，以便知道机器人还没死掉。。。

**Comment by SnapdragonLee** [comment]
> 有时候回复等待时间较长，建议可以在一定秒数后输出“请耐心等待”之类的提示，以便知道机器人还没死掉。。。
> 
> 

emm，这个我希望可以做一个小接口，或者说把错误栈也可以发送出来，机器人可以增强的地方太多了，可能需要几个版本以后，当然也许就是下一次更新才能改这个hhh

**Comment by karrisonX** [comment]
首先感谢作者的维护。目前这种实现方式的回复时间确实有点长了，是否考虑增加chatgpt3.5-turbo这一可选项呢，后者回复速度上会快很多，准确性也还好

**Comment by SnapdragonLee** [comment]
> 首先感谢作者的维护。目前这种实现方式的回复时间确实有点长了，是否考虑增加chatgpt3.5-turbo这一可选项呢，后者回复速度上会快很多，准确性也还好

可以加，但是对于上下文联想来说消耗的token会成倍增长，其余没有难度

**Comment by tommyxps** [comment]
我认为目前不必急于采用3.5-turbo，因为尽管它速度快、内容更加开放，但在微信这样的平台上使用容易受到封禁。另外，由于token的高消耗，使用3.5-turbo可能并不比目前的网页版更划算。

**Comment by SnapdragonLee** [comment]
#40
