### ISSUE TITLE
有个关于调用网页版的疑问

### ISSUE THREAD

**Issue by yikwongee** [SnapdragonLee/ChatGPT-weBot#28]
为什么不使用api去调用呢，这样的话聊天消息对话不就可以减少一些网页端的限制吗？谢谢

**Comment by SnapdragonLee** [comment]
> 为什么不使用api去调用呢，这样的话聊天消息对话不就可以减少一些网页端的限制吗？谢谢

原因在于，api调用最大对话限制是4096token，无法做到超长上下文回应。

另外，由于做这个需要自己存储上下文结构，所以需要大幅调整程序结构，因此暂时不考虑及时更新这一项。

**Comment by cappiewu** [comment]
> 为什么不使用api去调用呢，这样的话聊天消息对话不就可以减少一些网页端的限制吗？谢谢

用api调算token，要钱，用web版的逆向api是免费的。
另外web版的模型是针对自然语言对话做过微调的，效果要比官方api的对话效果好一点

**Comment by SnapdragonLee** [comment]
但是现在问题就是OpenAI把官方的endpoint给关了，这就很麻

**Comment by Ultrasteve** [comment]
> 

网页版不需要消耗token吗？

**Comment by Delppine1024** [comment]
不消耗token，同一个账号免费跑这个，也可以使用消耗token的API，都可以用，token消耗完了可以挂着这个

**Comment by SnapdragonLee** [comment]
现在还是可以使用的，API版本需要重写，我本人目前时间不是很能快速做完这个，谢谢理解

**Comment by SnapdragonLee** [comment]
已经更新 v1.0 了，欢迎大家尝试API版本
