### ISSUE TITLE
有时会卡住，需要在终端里按一下回车键才回复

### ISSUE THREAD

**Issue by free-y** [SnapdragonLee/ChatGPT-weBot#29]
好多次，感觉运行python main.py的终端卡住了，终端的log里输出问题后就不再继续输出log
需要在终端里按一下回车
然后终端里才开始继续输出log，微信上立即收到机器人的回复

**Comment by SnapdragonLee** [comment]
> 好多次，感觉运行python main.py的终端卡住了，终端的log里输出问题后就不再继续输出log
> 
> 需要在终端里按一下回车
> 
> 然后终端里才开始继续输出log，微信上立即收到机器人的回复

明白了，我也有过这种问题，我会仔细研究哪里出了问题

**Comment by free-y** [comment]
> > 好多次，感觉运行python main.py的终端卡住了，终端的log里输出问题后就不再继续输出log
> > 需要在终端里按一下回车
> > 然后终端里才开始继续输出log，微信上立即收到机器人的回复
> 
> 明白了，我也有过这种问题，我会仔细研究哪里出了问题

在网上看到类似的问题 https://jingyan.baidu.com/article/ce09321bb95dda2bff858f26.html 我先试试

**Comment by free-y** [comment]
试了那个方法，仍然有这个问题存在

**Comment by SnapdragonLee** [comment]
具体问题应该是 pingpong的周期过于短了，所以会导致这种问题

**Comment by tommyxps** [comment]
> 试了那个方法，仍然有这个问题存在

我之前也有这个问题 这个方案解决了

**Comment by skyyaman** [comment]
用pythonw 后台运行

**Comment by free-y** [comment]
> pythonw

如果同时我还想查看log，怎么办呢，有办法吗

**Comment by SnapdragonLee** [comment]
你可以调用重定向把print的东西打印出来

**Comment by SnapdragonLee** [comment]
反代服务器已经临时更新，顺便修复了可能的bug：

websocket可能无缘无故卡住
不再自动打印websocket的debug信息，精简命令行显示
尝试修复了chunkedlength 0 error，通过阅读代码，取消stream流失传输可能引发的握手失败、连接中断等引发的顶层报错
多账户功能依然没有引入，会在明后天引入这个功能
另外有兴趣开发机器人或想贡献代码的同志可以联系我，主页有我联系方式

**Comment by free-y** [comment]
我这边用的是发布的最新代码，还是有这个问题

**Comment by SnapdragonLee** [comment]
请使用requirements.txt中标注的websocket-client版本，我自己测试发现1.0以上会有卡住的情况，如果有问题欢迎开新帖子或重新打开这个帖子

**Comment by free-y** [comment]
使用了最新的repo，仍然有这个问题
