### ISSUE TITLE
似乎还不行 没反应 完全按照你的步骤

### ISSUE THREAD

**Issue by damingsi** [SnapdragonLee/ChatGPT-weBot#3]
测试了一下最新版本的 似乎还不行
![20230222](https://user-images.githubusercontent.com/79279990/220521695-e502158c-e0b8-4bd2-b8d8-efbf7b08b249.png)

**Comment by SnapdragonLee** [comment]
更新了没，没更新的话记得把rev_config.json里面的access_token键直接删掉就行。

**Comment by damingsi** [comment]
> 更新了没，没更新的话记得把rev_config.json里面的access_token键直接删掉就行，不要留下这个键

用的你昨天更新的版本 ChatGPT-weBot-0.90-dev

**Comment by SnapdragonLee** [comment]
> 

代码部分要更新到最新吧，git pull 同步一下代码吧

**Comment by damingsi** [comment]
log里面 只有心跳记录

**Comment by SnapdragonLee** [comment]
> log里面 只有心跳记录

哦对，是两种办法选一个，不能又注入，又开funtool

**Comment by damingsi** [comment]
可以了 你教程里应该标注一下二选一 两个都开会有问题

**Comment by SnapdragonLee** [comment]
> 可以了 你教程里应该标注一下二选一 两个都开会有问题

其实我有写，一会有时间我补一下中文文档吧，谢谢

**Comment by lsq33123** [comment]
我可以用其他版本的微信和dll么

**Comment by lsq33123** [comment]
![image](https://user-images.githubusercontent.com/29998078/220554617-b8b89818-fe36-4c35-ad16-0d149e4fa379.png)
我这个也是没反应 咋回事

**Comment by SnapdragonLee** [comment]
> 

不是很行，因为不同的dll注入导致的接口都不太一样，所以 嗯

**Comment by SnapdragonLee** [comment]
> 可以了 你教程里应该标注一下二选一 两个都开会有问题

我检查了一下我的文档，和你道歉。我之前以为自己写了，但其实并没有写。抱歉兄弟
