### ISSUE TITLE
ChatGPT response内容错误

### ISSUE THREAD

**Issue by free-y** [SnapdragonLee/ChatGPT-weBot#30]
刚才发现不能用了，Console里日志有输出如下内容
```
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by padoru233** [comment]
同样的报错

> Microsoft Windows [版本 6.3.9600]

(c) 2013 Microsoft Corporation。保留所有权利。

C:\server\ChatGPT-weBot>python main.py
--- request header ---
GET / HTTP/1.1
Upgrade: websocket
Host: 127.0.0.1:5555
Origin: http://127.0.0.1:5555
Sec-WebSocket-Key: YfOD29GdQ280Y/k/13ECzg==
Sec-WebSocket-Version: 13
Connection: Upgrade


-----------------------
--- response header ---
HTTP/1.1 101 Switching Protocols
Connection: Upgrade
Sec-WebSocket-Accept: P5HcFRiXC9b3xnan5YjU9wHkl7Y=
Server: WebSocket++/0.8.2
Upgrade: websocket
-----------------------

ChatGPT login test success!

send: b'\x81\xeeiP/Y\x12rF=Kj\x0f{[`\x1djYc\x1f`Yi\x1e`Yc\ruIr[ \x195\rcIf\x1aiY
|\x0f{\x1e(F=Kj\x0f{;\x1f`\rK|\x0f{\x1b?@4\x004\rcIr\ruIrL6\x07$J7\x1dr\x15yKr\x
03yK>F:\x02>N4\x0cr\x15yKr\x03yK5W-Kj\x0f{K-'
{'content': '{"wx_code":"","wx_id":"wxid_s4c9765onbag22","wx_name":"布布"}', 'id
': '20230309091903', 'receiver': 'CLIENT', 'sender': 'SERVER', 'srvid': 1, 'stat
us': 'SUCCSESSED', 'time': '2023-03-09 09:19:03', 'type': 6500}
{'content': '在吗', 'id': '20230309092027', 'id1': '', 'id2': '', 'id3': '', 'sr
vid': 1, 'time': '2023-03-09 09:20:27', 'type': 1, 'wxid': 'wxid_i6mqgk61v6e422'
}
ask:在吗
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>

Exception in thread Thread-5:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\threa
ding.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\server\ChatGPT-weBot\multithread\threads.py", line 23, in run
    item.play()
  File "C:\server\ChatGPT-weBot\basic\task.py", line 50, in play
    for data in self.bot.ask(
  File "C:\server\ChatGPT-weBot\revChat\revChatGPT.py", line 184, in ask
    self.__check_response(response)
  File "C:\server\ChatGPT-weBot\revChat\revChatGPT.py", line 246, in __check_res
ponse
    raise error
revChat.revChatGPT.Error
send: b'\x89\x80\x03\x06\r\x96'
{'content': '-h', 'id': '20230309092238', 'id1': '', 'id2': '', 'id3': '', 'srvi
d': 1, 'time': '2023-03-09 09:22:38', 'type': 1, 'wxid': 'wxid_i6mqgk61v6e422'}
reply: 欢迎使用 ChatGPT-weBot ，本项目在 github 同名开源
-h 查看可用命令帮助
-i 提问AI画图机器人(仅英语)
 提问聊天机器人
-rs 重置上下文
-rg 重新生成答案
-rb +数字n 回滚到倒数第n个问题
send: b'\x81\xfe\x02"M\x98U\xd66\xba<\xb2o\xa2u\xf4\x7f\xa8g\xe5}\xabe\xef}\xa1g
\xe4~\xa0w\xfam\xba!\xaf=\xfdw\xecm\xad`\xe3a\xb8w\xa15\xf11\xf4w\xb8w\xa15\xf11
\x89$\xae8\xa7*\xf3c\xe7;\xae0\xe2\x7f\xaaw\xfam\xba\'\xb9"\xf5<\xb2o\xa2u\xf4o\
xb4u\xf4.\xf7;\xa2(\xf6!\xf4w\xb8w\x8a8\xae7\xe4\x7f\xc4 \xee+\xfb0\x8a8\xac3\xe
1+\xc4 \xe1x\xaam\xf6\x0e\xf04\xa2\n\xc8\x01\xfb:\xfd\x17\xb99\xb8\t\xa3+\xfee\x
b5\x11\xedc\xe1\x7f\xfb\t\xa3t\xa0b\xef\x11\xedb\xe0(\xfd\t\xa3x\xafg\xeem\xff<\
xa2%\xed7\xf6\x11\xed`\xe2}\xfb\t\xa3x\xace\xb2\x11\xed`\xb0}\xa8\t\xa3{\xfdl\xe
6\x11\xf6x\xbem\xc4 \xe0z\xfd`\x8a8\xafb\xe6/\xc4 \xe3~\xfd3\x8a8\xaf`\xe4u\xc4
\xe3y\xaf1\x8a8\xac0\xb3y\xc4 \xe3(\xaa0\x8a8\xadg\xb7t\xc4;\xfb$\xb8\t\xa3{\xab
1\xe6\x11\xedl\xe3(\xfd\x14\x9f\x11\xedb\xe3~\xfa\t\xa3x\xae3\xb3\x11\xedc\xe1~\
xf9\t\xa3x\xaec\xee\x11\xeda\xb3/\xf9}\x8a8\xac0\xb5x\xc4 \xee\x7f\xfed\x8a8\xa0
7\xb3)\xb1\t\xb8m\xc4 \xe0~\xfce\x8a8\xa1`\xb3(\xc4 \xee}\xac4\x8a8\xadl\xe4t\xc
4 \xe0z\xab4\x8a8\xadc\xe0u\xc4 \xe2(\xfa4\x8a#\xb5\'\xa5m\xc4 \xef|\xfb1\x8a8\x
af3\xe0(\xc4 \xe2(\xa84\x8a8\xac0\xe6/\xc4 \xe0x\xa0b\x8a#\xb5\'\xb1m\xc4 \xef|\
xfb1\x8a8\xae`\xb4}\xc4 \xe1x\xa93\x8a8\xaeg\xe7}\xc4 \xe1/\xada\x8a8\xaem\xe2u\
xc4;\xfb?\xfau\xfd\x11\xedc\xe3z\xa8\t\xa3x\xfa`\xe1#\xb8\t\xa3x\xae1\xb3\x11\xe
dc\xb3)\xf9\t\xa3x\xaaf\xe6\x11\xed`\xe6|\xaa\t\xa3{\xadb\xe6\x11\xedb\xb4\x7f\x
fb;\x8a8\xac0\xe4,\xc4 \xefx\xfd0\x8a8\xa1m\xefu\xbay\xf6o\xf6<\xb5&\xf64\xbb(\x
bao\xf6o\xbay\xf6o\xfd-\xa2o\xa2u\xf4o\xe5'
{'content': 'send txt msg:asm execution succsessed', 'id': '20230309092238', 're
ceiver': 'CLIENT', 'sender': 'SERVER', 'srvid': 1, 'status': 'SUCCSESSED', 'time
': '2023-03-09 09:22:38', 'type': 555}
send: b'\x89\x80\xdc\x01\x97\xd1'

**Comment by tommyxps** [comment]
确实 有相同问题

**Comment by SnapdragonLee** [comment]
[#1090](https://github.com/acheong08/ChatGPT/issues/1090) Same issue reference

**Comment by Ultrasteve** [comment]
用api_key那种方式来调用是不是会更稳定呢，我自己挂了代理用这个项目，成功率挺低的（也有可能是代理被ban了的问题）

**Comment by SnapdragonLee** [comment]
> 用api_key那种方式来调用是不是会更稳定呢，我自己挂了代理用这个项目，成功率挺低的（也有可能是代理被ban了的问题）

正确的，我会尽快更新API版本的调用，但更大概率会在1天后的集中维护中集中呈现

**Comment by Ultrasteve** [comment]
> > 用api_key那种方式来调用是不是会更稳定呢，我自己挂了代理用这个项目，成功率挺低的（也有可能是代理被ban了的问题）
> 
> 正确的，我会尽快更新API版本的调用，但更大概率会在1天后的集中维护中集中呈现

: ) 辛苦大佬啦

**Comment by tommyxps** [comment]
> 用api_key那种方式来调用是不是会更稳定呢，我自己挂了代理用这个项目，成功率挺低的（也有可能是代理被ban了的问题）

应该是你代理问题 我国外ip 成功率接近100%

**Comment by SnapdragonLee** [comment]
不过同志们不用担心，我依然还有不走token的方式，但是我不能明说，大家可以回头自己看文档

**Comment by suleil1** [comment]
> > 用api_key那种方式来调用是不是会更稳定呢，我自己挂了代理用这个项目，成功率挺低的（也有可能是代理被ban了的问题）
> 
> 应该是你代理问题 我国外ip 成功率接近100%

更换了VPN地区之后还是404，应该不是IP被ban的原因，这个接口应该被openAI关闭了，需要尝试其他方法了。

**Comment by SnapdragonLee** [comment]
可以改，现在需要重写逻辑，因为上下文对话方式已经全部更改掉了，需要重写之前revchatgpt给出的所有底层接口

**Comment by joe12801** [comment]
是反向代理挂了

**Comment by free-y** [comment]
SnapdragonLee大佬，弱弱的问一下，什么时候能修复这个问题呢？

**Comment by joe12801** [comment]
官方已经更新最新反向代理，可以用了

**Comment by free-y** [comment]
> 官方已经更新最新反向代理，可以用了

我这边怎么还是报这个错误

**Comment by damingsi** [comment]
![111](https://user-images.githubusercontent.com/79279990/224230863-7addc816-38a8-4ef7-af48-413c7234a560.png)
还是有问题

**Comment by free-y** [comment]
> ![111](https://user-images.githubusercontent.com/79279990/224230863-7addc816-38a8-4ef7-af48-413c7234a560.png) 还是有问题

看这里 https://github.com/SnapdragonLee/ChatGPT-weBot/issues/33

**Comment by SnapdragonLee** [comment]
确实是有问题的，不稳定大于稳定才是最正常的 哈哈

**Comment by SnapdragonLee** [comment]
反代服务器已经临时更新，顺便修复了可能的bug：
1. websocket可能无缘无故卡住
2. 不再自动打印websocket的debug信息，精简命令行显示
3. 尝试修复了chunkedlength 0 error，通过阅读代码，取消stream流失传输可能引发的握手失败、连接中断等引发的顶层报错
4. 多账户功能依然没有引入，会在明后天引入这个功能
另外有兴趣开发机器人或想贡献代码的同志可以联系我，主页有我联系方式

**Comment by SnapdragonLee** [comment]
最新的大更新 #40
