### ISSUE TITLE
按说明配置好以后报错显示连接太多

### ISSUE THREAD

**Issue by ziyuan888** [SnapdragonLee/ChatGPT-weBot#36]
显示成功登录chatgpt，网页也试过登录没问题
一但输入消息就报如下错误
requests.exceptions.SSLError: HTTPSConnectionPool(host='apps.openai.com', port=443): Max retries exceeded with url: /api/conversation (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)')))

**Comment by skyyaman** [comment]
同

**Comment by SnapdragonLee** [comment]
是否更新过代码？
如果已经拉取到了最新版本，请注意开启全局代理，如果还有这个问题可以等待 #40

**Comment by SnapdragonLee** [comment]
最新的API调用可以解决这个问题，请更新代码
