### ISSUE TITLE
自动重置

### ISSUE THREAD

**Issue by Evander0** [SnapdragonLee/ChatGPT-weBot#37]
当api过于拥挤：We're currently processing too many requests. Please try again later. 后机器人不会自动重置，需要手动重启

**Comment by joe12801** [comment]
现在这情况，反馈 叫作者增加多账号

**Comment by SnapdragonLee** [comment]
好的，我会研究一下error做重试，需要时间做一下测试

**Comment by SnapdragonLee** [comment]
#40
