### ISSUE TITLE
都是完全按照教程去做的，但是没有回复没有响应？

### ISSUE THREAD

**Issue by luckydzj** [SnapdragonLee/ChatGPT-weBot#39]
难道还要另外开代理吗？我用注入ddl的方式以及funtool的方式，都试过了，token也配置上去，但是不管怎么样都没有响应

**Comment by luckydzj** [comment]
> 开始的时候会有 login success 提示，你这里有显示嘛

是执行python main.py 后吗？好像是没有loging success

**Comment by luckydzj** [comment]
> 开始的时候会有 login success 提示，你这里有显示嘛
这个吗？
![image](https://user-images.githubusercontent.com/39119892/225036529-68c25c97-3113-42b7-9ee9-28257b9763f7.png)

**Comment by SnapdragonLee** [comment]
是的，login没有成功需要检查session_token对不对，然后代理通道是否可以让运行环境的流量通过
