### ISSUE TITLE
没有回复 已经拉取了最新的代码【2023年2月22日16:20:18】

### ISSUE THREAD

**Issue by lsq33123** [SnapdragonLee/ChatGPT-weBot#4]
![image](https://user-images.githubusercontent.com/29998078/220562899-d3a917ca-1cd5-48d0-8332-221f5d1805c2.png)
有监听到消息  但是没有回复了

**Comment by SnapdragonLee** [comment]
注意看readme，需要设置的

**Comment by SnapdragonLee** [comment]
已经更新中文文档，请仔细阅读中文文档，依然有问题可以重新打开本issue
