### ISSUE TITLE
集中更新2023.3.21

### ISSUE THREAD

**Issue by SnapdragonLee** [SnapdragonLee/ChatGPT-weBot#40]
下一个版本是正式版，会在明天开始集中测试后发布，这两周太忙了，一直没有大把时间搞这个。
具体的改进目标如下：
1. 转移到 gpt3.5-turbo 的 API 调用
2. 尽可能的异常处理
3. 解决异常退出后需要手动重启服务的问题
4. webchatgpt功能嵌入
5. 人格设定 character_desc（以及更多的设定）
6. 图像生成的正负prompt
7. 全部使用API_token登录
8. readme完善
9. 有哥们 姐姐想buy me coffee的话，可以但是不要多，公益发电，为爱奉献

实验性（绕过 requests 频率限制，多账号回复支持，使用session_token登录，取消账号密码登录）

**Comment by ziyuan888** [comment]
期待

**Comment by joe12801** [comment]
为什么要取消邮箱登录，session_token 一定月要换一次啊

**Comment by SnapdragonLee** [comment]
新的任务已经更新，这次更新主要位于底层API替换

**Comment by joe12801** [comment]
为什么要取消 邮箱和密码登录

**Comment by SnapdragonLee** [comment]
因为邮箱密码登录会把账号信息泄露给不受信任的服务器，用accesstoken可能会规避这个问题

**Comment by SnapdragonLee** [comment]
前7项全部完成，已经进入测试阶段

**Comment by SnapdragonLee** [comment]
很遗憾，我自己处理了很多逻辑的bug，但是文档没有编写，多出了很多很多参数，放出来大家也没法测试

**Comment by SnapdragonLee** [comment]
已经更新，大家可以更新代码库了
