### ISSUE TITLE
我的openai账号被封了，报account deactived，是代理导致，请先暂时停用本项目

### ISSUE THREAD

**Issue by Ultrasteve** [SnapdragonLee/ChatGPT-weBot#41]

**Comment by free-y** [comment]
我的几个号也有这个问题

**Comment by SnapdragonLee** [comment]
我怀疑是一个账号问问题太多了导致的

**Comment by SnapdragonLee** [comment]
或者是使用API轮询次数太多？或者没有挂代理导致，你是只用了这个项目的嘛，纯用chatgpt不会导致这个问题

**Comment by free-y** [comment]
我的俩个号都在这个项目里使用过，被封了。

**Comment by Ultrasteve** [comment]
> 或者是使用API轮询次数太多？或者没有挂代理导致，你是只用了这个项目的嘛，纯用chatgpt不会导致这个问题

只用了这个项目，代理是挂了的。

**Comment by Ultrasteve** [comment]
> 我的俩个号都在这个项目里使用过，被封了。

老哥你也是纯用这个项目没用apikey吗

**Comment by Evander0** [comment]
> 我怀疑是一个账号问问题太多了导致的

我问题问的不多，一般一天不会超过5个，而且好像封的时间都差不多
我是今天早上11点发现的

**Comment by nulshell** [comment]
今天我的账号也被关了。在墙外不需要代理，问的也不多，主要是给国内家里人体验一下。在想会不会是因为多线程，或者是新版的临时反代地址被发现的缘故？

**Comment by nulshell** [comment]
> 

我刚开始试过API连接感觉回复比较笨，以及另一种用命令行模拟浏览器连接过一段时间就会断联。很喜欢这个项目的网页版连接，感谢作者👍，聊天交流及上下文关联都很不错，如果不能用真太可惜了。不知道，是不是越接近真实的网页版连接的方式越好，以前的单线程也觉得够好的了。当然在浏览器上打开多个窗口同时问不同问题可能也是有人会用到的真实场景，或许不太多。

**Comment by nulshell** [comment]
或者是需要把 rev_config.json 里面的 "paid": true 改成 false才对吗？我的是免费试用$18的账户，只填了token没有改 "paid" 项。

**Comment by joe12801** [comment]
我用QQ机器人，网页chatgpt也被封号了

**Comment by SnapdragonLee** [comment]
貌似没有什么关系，现在好像很多人都被封了，具体可以看 [#1158](https://github.com/acheong08/ChatGPT/issues/1158)

**Comment by SnapdragonLee** [comment]
请更新代码到v1.00改用API-token方式调用API，避免封号问题

**Comment by Kevinwang-138937492874982749827** [comment]
> 我怀疑是一个账号问问题太多了导致的

不是。。我有一个账号就问了 5 个问题，就说 account deleted or deactivated
