### ISSUE TITLE
无法监听发过来的消息5555

### ISSUE THREAD

**Issue by BarryAllen-Arrow** [SnapdragonLee/ChatGPT-weBot#42]
python main.py运行了以后，可以看到login success的提示
![image](https://user-images.githubusercontent.com/117068591/225275015-59211862-754e-4ef0-a88b-3c172c57952d.png)
但是别人发过来的消息，都不能监听到

**Comment by SnapdragonLee** [comment]
请先不要使用这个方式，会导致封号

**Comment by SnapdragonLee** [comment]
另外，命令行不要选择字符，选择的时候进程会处于暂停状态

**Comment by BarryAllen-Arrow** [comment]
好的！感谢！！我用另外那个方法，完美解决！
