### ISSUE TITLE
请求支持OpenAI官方gpt3.5-turbo的API调用

### ISSUE THREAD

**Issue by KarlLee830** [SnapdragonLee/ChatGPT-weBot#43]
现有的方式感觉都不太稳妥，请求直接调用官方的API，让用户可以自己选择是用session token还是API。
这样也能更好的支持未来的ChatGPT 4模型的调用。

**Comment by SnapdragonLee** [comment]
好的我尽快做 只能说现在这个情况 非Plus用户使用代理用API依然有可能封禁

**Comment by SnapdragonLee** [comment]
我需要首先了解一下文档

**Comment by SnapdragonLee** [comment]
#40
