### ISSUE TITLE
openai限流非常夸张！问几个问题就会报错"Too many question within 1 hour"。是否有办法bypass这个？

### ISSUE THREAD

**Issue by BarryAllen-Arrow** [SnapdragonLee/ChatGPT-weBot#44]
如题~

**Comment by BarryAllen-Arrow** [comment]
btw还有一个小问题~每次被限流以后，好像都要我手动退出程序(powershell窗口)，再重启。但是这样做的话，之前储存的对话好像就都不见了(记忆清空了)。有没有办法在重启服务的同时，保留之前的对话？

**Comment by SnapdragonLee** [comment]
这个办法没法bypass，现在全靠魔改acheong08/chatgpt的V1，后面主推API版本

**Comment by joe12801** [comment]
啥时，能多账号啊

**Comment by SnapdragonLee** [comment]
v1.00更改了调用，成为API调用模式，暂时弃用chatgpt调用方式
