### ISSUE TITLE
能否在重启程序(关闭指令窗再新建一个，运行python)以后，还能保留/获取到之前的对话记录？

### ISSUE THREAD

**Issue by BarryAllen-Arrow** [SnapdragonLee/ChatGPT-weBot#45]
如题。因为我发现，有时候被限流或者别的错误后，机器人不会自行恢复，必须得重新启动程序才能让它继续运转。但是重新启动程序以后，会丢失所有的对话id。有没有办法将每个微信号(私信的和群聊的)的对话id，作为json文件存在服务器本地？并在每次有人提问时都尝试从这些json文件里，找到他对应的文件，并获取他的对话id？

**Comment by BarryAllen-Arrow** [comment]
![0faf1a11921354725a007332e8c4644](https://user-images.githubusercontent.com/117068591/225518092-2f206a87-7b3d-49d7-9300-eb1b894ccdeb.png)
还有个问题55555，每次程序碰到问题以后，比如说conversation not found，或者限流，它永远都不会自动恢复，监听还是照常，能监听到微信的消息，但是不会继续自动恢复了。它会直接就停止工作了...必须要我手动重启才行。这种问题怎么解决？

**Comment by Evander0** [comment]
> ![0faf1a11921354725a007332e8c4644](https://user-images.githubusercontent.com/117068591/225518092-2f206a87-7b3d-49d7-9300-eb1b894ccdeb.png) 还有个问题55555，每次程序碰到问题以后，比如说conversation not found，或者限流，它永远都不会自动恢复，监听还是照常，能监听到微信的消息，但是不会继续自动恢复了。它会直接就停止工作了...必须要我手动重启才行。这种问题怎么解决？

@BarryAllen-Arrow 这个会统一修：#40
