### ISSUE TITLE
使用-rs以后，经常会出现"conversation not found"的bug

### ISSUE THREAD

**Issue by BarryAllen-Arrow** [SnapdragonLee/ChatGPT-weBot#46]
如题。使用-rs清空以后，再问问题，总会有几率触发conversation not found的错误。而且头大的是，它一旦报错，就一直错下去了，后面新的问题它再也不会继续去问...

**Comment by BarryAllen-Arrow** [comment]
![image](https://user-images.githubusercontent.com/117068591/225564333-34241934-e2f4-46b7-8f0b-63fa9f9a0275.png)
如图，就是这个错误。出现以后，我不重启，机器人就无法正常运转

**Comment by BarryAllen-Arrow** [comment]
我测试了两天，感觉现在最大的问题是，一旦它因为什么原因无法回答(可能是openai限流，或者openai报错，或者-rs清除对话以后，对话id跟网页端对不上各种原因)，整个程序就死掉，不会自动恢复，也不会继续接收问题。只能重启。但是一重启，所有的对话就都没了

**Comment by SnapdragonLee** [comment]
是的，这是因为创建的任务还没有经过执行，而是产生了chatbot对象而没有调用分配conversation id导致的，这部分也缺少error handler

**Comment by SnapdragonLee** [comment]
#40
