### ISSUE TITLE
需要的功能可在这留言

### ISSUE THREAD

**Issue by SnapdragonLee** [SnapdragonLee/ChatGPT-weBot#5]
需要的功能可在这留言，我会在斟酌可行性后在各个版本加入

**Comment by tiwentichat** [comment]
https://github.com/zhayujie/chatgpt-on-wechat 这个项目的config设置里面有个人格设定 character_desc，感觉这个功能很赞啊，大佬可以搞进去不

**Comment by SnapdragonLee** [comment]
> 

已阅

**Comment by SnapdragonLee** [comment]
> https://github.com/zhayujie/chatgpt-on-wechat 这个项目的config设置里面有个人格设定 character_desc，感觉这个功能很赞啊，大佬可以搞进去不

已阅

**Comment by Shmily40** [comment]
是否考虑出一个linux系统的版本

**Comment by lzcwy** [comment]
大佬可不可以提个需求，增加群消息总结功能，例如发送关键字命令之后，将本群成员发送过的消息喂给chatgpt总结，下一次再总结时清空上次总结的内容

**Comment by SnapdragonLee** [comment]
> 大佬可不可以提个需求，增加群消息总结功能，例如发送关键字命令之后，将本群成员发送过的消息喂给chatgpt总结，下一次再总结时清空上次总结的内容

可以，但需要更多细节，欢迎单开新帖详细描述

**Comment by SnapdragonLee** [comment]
> 是否考虑出一个linux系统的版本
> 
> 

暂时没有头绪不考虑，主要是不知道怎么做。linux用wine模拟系统调用，但我不知道中间是否有工具可以注入内存之类的，我不太清楚这方面有没有什么参考资料。

**Comment by knigth95** [comment]
希望加个服务器（linux）端的版本以及增加生成图片的功能0.0

**Comment by suyunkai** [comment]
请问有没有什么方法能实现多开？或者3.60版本的微信独立存在。现在一台电脑登陆这个微信，就不能再登普通的了

**Comment by SnapdragonLee** [comment]
> 希望加个服务器（linux）端的版本以及增加生成图片的功能0.0

生成图片我也在希望做，但服务器端除了用wechaty等第三方工具链（我自己也写过，后来被封了2次），我确实不知道应该怎么做保证不封号。

**Comment by SnapdragonLee** [comment]
> 请问有没有什么方法能实现多开？或者3.60版本的微信独立存在。现在一台电脑登陆这个微信，就不能再登普通的了

我能提供一个免安装版本，可以直接拷贝后启动使用，双开可以通过脚本实现，这个没有难点，已经更新

**Comment by damingsi** [comment]
// 查看可用命令帮助
  "helpKey": "-h",
  // 设置重置上下文关键词
  "resetChatKey": "-rs",
  // 设置重新生成答案关键词
  "regenerateKey": "-rg",
  // 设置回滚到以前的n个问题关键词
  "rollbackKey": "-rb"
}
这些好像不起作用

**Comment by SnapdragonLee** [comment]
> 

 请clone到最新的 commit 代码

**Comment by SnapdragonLee** [comment]
> // 查看可用命令帮助 "helpKey": "-h", // 设置重置上下文关键词 "resetChatKey": "-rs", // 设置重新生成答案关键词 "regenerateKey": "-rg", // 设置回滚到以前的n个问题关键词 "rollbackKey": "-rb" } 这些好像不起作用

请clone到最新的 commit 代码

**Comment by damingsi** [comment]
> > // 查看可用命令帮助 "helpKey": "-h", // 设置重置上下文关键词 "resetChatKey": "-rs", // 设置重新生成答案关键词 "regenerateKey": "-rg", // 设置回滚到以前的n个问题关键词 "rollbackKey": "-rb" } 这些好像不起作用
> 
> 请clone到最新的 commit 代码

我之前把“-c” 改成了 “” 结果后面的-h -rs -rg -rb都不起作用了 刚才用默认的就没事了 是否有办法既可以不打-c又能使用其他的命令？

**Comment by joe12801** [comment]
希望增加多个chatgpt账号的功能，当然第一个账号回答次太多了，被限制了，就会自己切换到第二个账号

**Comment by SnapdragonLee** [comment]
> 希望增加多个chatgpt账号的功能，当然第一个账号回答次太多了，被限制了，就会自己切换到第二个账号

已经提上日程

**Comment by SnapdragonLee** [comment]
> > > // 查看可用命令帮助 "helpKey": "-h", // 设置重置上下文关键词 "resetChatKey": "-rs", // 设置重新生成答案关键词 "regenerateKey": "-rg", // 设置回滚到以前的n个问题关键词 "rollbackKey": "-rb" } 这些好像不起作用
> 
> > 
> 
> > 请clone到最新的 commit 代码
> 
> 
> 
> 我之前把“-c” 改成了 “” 结果后面的-h -rs -rg -rb都不起作用了 刚才用默认的就没事了 是否有办法既可以不打-c又能使用其他的命令？

可以有，我的优先级是先判断提问，后判断其他指令，我后面会调整一下结构支持这个选项

**Comment by xy185** [comment]
> > https://github.com/zhayujie/chatgpt-on-wechat 这个项目的config设置里面有个人格设定 character_desc，感觉这个功能很赞啊，大佬可以搞进去不
> 
> 已阅，会等待更多的人提出需求，来权衡是否加入。

这个应该会有很多应用场景，同求加入

**Comment by Wen2chao** [comment]
可以加入并发处理对话吗？目前看起来是单线程

**Comment by SnapdragonLee** [comment]
> 可以加入并发处理对话吗？目前看起来是单线程

chatgpt是单线程处理，目前想要多线程仅有的方式是多账号

**Comment by SnapdragonLee** [comment]
> 

已经更新

**Comment by SnapdragonLee** [comment]
> 请问有没有什么方法能实现多开？或者3.60版本的微信独立存在。现在一台电脑登陆这个微信，就不能再登普通的了

已经更新

**Comment by SnapdragonLee** [comment]
> 

很遗憾，我不认为这样做有任何好处，由于支持上下文联想，如果这样做凭空增加了很多没有意义的、可以预见性的工作量，谢谢您的理解

**Comment by SnapdragonLee** [comment]
> > 需要的功能可在这留言，我会在斟酌可行性后在各个版本加入
> > 能不能键入指令后开启ai模式，然后之后的每次对话都不用再加指令就能和chatgpt聊天了，再加个结束ai模式的指令，结束之后chatgpt就不会自动回复了，这样就能保证流畅地聊天了，现在如果把激活指令设为空的话，chatgpt会回复所有消息，很影响使用

很遗憾，我不认为这样做有任何好处，由于支持上下文联想，如果这样做凭空增加了很多没有意义的、可以预见性的工作量，谢谢您的理解

**Comment by jinshuguangze** [comment]
上述说的人格设定+1
然后不知道文字-图片生成能不能搞呢？

**Comment by tommyxps** [comment]
是否可以像 https://github.com/qunash/chatgpt-advanced 一样，加入对最近web 内容的解读，然后返回内容？

**Comment by SnapdragonLee** [comment]
> 上述说的人格设定+1 然后不知道文字-图片生成能不能搞呢？

请更新至0.99-dev，使用stable-diffusion的txt2img简单应用已经嵌入
人格设定还没有时间搞

**Comment by SnapdragonLee** [comment]
> 是否可以像 https://github.com/qunash/chatgpt-advanced 一样，加入对最近web 内容的解读，然后返回内容？

我会仔细研究这个的，我也关注到这个了，谢谢你的留言

**Comment by tommyxps** [comment]
> > 是否可以像 https://github.com/qunash/chatgpt-advanced 一样，加入对最近web 内容的解读，然后返回内容？
> 
> 我会仔细研究这个的，我也关注到这个了，谢谢你的留言

谢谢！

**Comment by SnapdragonLee** [comment]
> 

完全可以做到，但是不推荐推广给大家，这部分不难您可以自己DIY。如果没什么头绪，也可以指导

**Comment by SnapdragonLee** [comment]
> 有个新功能的想法，关于定时启动和关闭的
> 
> 起因是部署的的一个机器人在群里坚持两天后，被微信以骚扰他人涉嫌营销的理由封禁，虽然再注册一个微信号也没有什么难，但还是想能否添加一个功能，定时启动关闭，比如
> 
> 如果是群聊，北京时间x点开始，y关闭 如果是私聊，则一直开启（当然也可以向群聊一样添加时间限制）
> 
> 这样的功能能实现么？
> 
> 感谢

完全可以做到，但是不推荐推广给大家，这部分不难您可以自己DIY。如果没什么头绪，也可以指导

**Comment by lpflhh** [comment]
> https://github.com/zhayujie/chatgpt-on-wechat 这个项目的config设置里面有个人格设定 character_desc，感觉这个功能很赞啊，大佬可以搞进去不

同问，这个设定不错

**Comment by SnapdragonLee** [comment]
> https://github.com/zhayujie/chatgpt-on-wechat 这个项目的config设置里面有个人格设定 character_desc，感觉这个功能很赞啊，大佬可以搞进去不

我有仔细阅读这里面做的东西，大部分人做的都是一样的，就是在开始对话时首先传入强设定喂给chatgpt并进行对话，但我实际测试来看，对于网页版chatgpt，这个设定貌似很难成功，如果有稳定人设的方式可以留言

**Comment by SnapdragonLee** [comment]
> 可以加入并发处理对话吗？目前看起来是单线程

主线程与问答线程已经通过模式分离，保证主进程稳定运行，但多账号我目前还没有完全填补，API已经留好了，等有时间我会尽快加上

**Comment by tiwentichat** [comment]
> > https://github.com/zhayujie/chatgpt-on-wechat 这个项目的config设置里面有个人格设定 character_desc，感觉这个功能很赞啊，大佬可以搞进去不
> 
> 我有仔细阅读这里面做的东西，大部分人做的都是一样的，就是在开始对话时首先传入强设定喂给chatgpt并进行对话，但我实际测试来看，对于网页版chatgpt，这个设定貌似很难成功，如果有稳定人设的方式可以留言

你是...你需要帮我...类似这样的句型都可以啊，后面加上：不需要和我做其他互动，不要做任何解释。如果你明白就开始/回复我"明白"。

https://tiwenti.chat 我分类的这些基本上都可以（连续测试的话，后面的新设定有的时候会被前面的设定影响，机制如此没办法，但是不连续换人设就没问题）

**Comment by zwjie12** [comment]
请问可以在群晖docker上运行吗？貌似没搜到现成的镜像

**Comment by SnapdragonLee** [comment]
docker上面我还没有尝试过 @zwjie12 ，等后续开发稳定以后我再来看这个

**Comment by wrhsd1** [comment]
建议在chatgpt没有响应或者错误的时候发送错误信息，提示服务暂时失效

**Comment by SnapdragonLee** [comment]
> 建议在chatgpt没有响应或者错误的时候发送错误信息，提示服务暂时失效

已经更新，上述讲的新功能几乎都包含

**Comment by SnapdragonLee** [comment]
@BruceWayne1950  好的我会研究

**Comment by formero009** [comment]
能否支持多个apikey 轮训调用？就是配置那里可以配置多个api_key 用某个分隔符分割，调用的时候依次使用不同的api调用，这样会有封号的风险吗？

**Comment by formero009** [comment]
还有就是能否添加一个配置项，可以开启或者关闭是否记住上下文，不开启上下文记忆感觉应该能省不少token，而且有的场景下不太需要记忆功能

**Comment by SnapdragonLee** [comment]
> 能否支持多个apikey 轮训调用？就是配置那里可以配置多个api_key 用某个分隔符分割，调用的时候依次使用不同的api调用，这样会有封号的风险吗？

会有封号风险

**Comment by SnapdragonLee** [comment]
> 还有就是能否添加一个配置项，可以开启或者关闭是否记住上下文，不开启上下文记忆感觉应该能省不少token，而且有的场景下不太需要记忆功能

emmm，我不建议添加这个，做机器人最大的亮点就是支持上下文，如果一直不要上下文，可以考虑 reset 对话。因为对于不需要记忆功能的问题，失去了这个项目的各种预置功能设置

**Comment by shuyaoyao** [comment]
可以考虑添加个长文回复转换成图片消息发送的功能，应该更容易避免骚扰封号的问题？

**Comment by rogue-shadowdancer** [comment]
可不可以加一个重启服务功能，有时候某个线程崩了重启下就好了，但是现在要登上服务器才能重启

**Comment by SnapdragonLee** [comment]
> 可不可以加一个重启服务功能，有时候某个线程崩了重启下就好了，但是现在要登上服务器才能重启

从原理上可以的，回去可以改一下

**Comment by padoru233** [comment]
希望能增加角色扮演中角色列表的查询

**Comment by SnapdragonLee** [comment]
> > 请问可以在群晖docker上运行吗？貌似没搜到现成的镜像
> 
> 群辉的DSM系统本质上是Linux+web图型界面。Docker的话...反正我的群辉跑个web都可费劲😂

下一个大版本之前我估计不会出现linux wine的部署方式，我会尽可能探索，因为确实服务器方便一些，但是我没办法保证一定可以出现这个办法

**Comment by SnapdragonLee** [comment]
> 希望能增加角色扮演中角色列表的查询

可以，我会增加这个办法在下一个更新中，但是需要一定时间

**Comment by Nanmen** [comment]
目前支持自己构建Stable Diffusion Model本地部署的画图AI 么？

**Comment by SnapdragonLee** [comment]
> 目前支持自己构建Stable Diffusion Model本地部署的画图AI 么？

原理上来说肯定可以，但我个人的电脑没办法做这个测试，www

**Comment by jk256** [comment]
当前的会话是否有类似超时设定，如果每次不连贯的上文都提交那会不会很浪费token，还是说如果没有达到设定的max_tokens需要经常手动操作-rs

**Comment by SnapdragonLee** [comment]
@jk256 是这样的

**Comment by jk256** [comment]
> @jk256是这样的

体验了几天，希望增加类似于会话超时功能的设定，可手动配置超时时间，超时后视为新会话。这样也可以通过设置短时间限制是否要联系上下文，我个人使用单次回答token很多，每次新提问前都需要记着先-rs，用多了有些糟心。希望你可以适当参考。

**Comment by SnapdragonLee** [comment]
可以的，下次增加一个单词对话超时时间

**Comment by jk256** [comment]
> 可以的，下次增加一个单词对话超时时间

大佬🐂🖊

**Comment by BarryAllen-Arrow** [comment]
能否添加@人的功能？就是回答问题的时候，在微信群里@提出问题的那个人

**Comment by BarryAllen-Arrow** [comment]
大佬大佬，我注意到用这个机器人的方法，机器人发出来的链接网址好像不是超链接，而是普通的文本，但是我手动复制粘贴发出去，又是超链接。有没有办法让机器人也能发送超链接呀？

**Comment by efwds** [comment]
有没有办法把https://github.com/zhayujie/chatgpt-on-wechat中的itchat便捷地替换成这里面客户端微信dll注入实现

**Comment by kamike** [comment]
-i生成的图片希望可以有地方配置张数，现在生成的图片好像最低4张，有时候出现8张。希望可以自己定义最大图片数量

**Comment by ahui9605** [comment]
请问可以增加微信语音消息的文字转换功能吗？ 比如，我发送给 ChatGPT 一个语音消息，然后 ChatGPT 自动将其转换为文字，知道我说了什么内容之后再进行回复。 可以用微信里自带的语音转文本或者openai的whisper。

**Comment by SnapdragonLee** [comment]
> 能否添加@人的功能？就是回答问题的时候，在微信群里@提出问题的那个人

这是我一直想做的，但很无奈dll不支持

**Comment by SnapdragonLee** [comment]
> -i生成的图片希望可以有地方配置张数，现在生成的图片好像最低4张，有时候出现8张。希望可以自己定义最大图片数量

每一次都是4张

**Comment by SnapdragonLee** [comment]
> 请问可以增加微信语音消息的文字转换功能吗？ 比如，我发送给 ChatGPT 一个语音消息，然后 ChatGPT 自动将其转换为文字，知道我说了什么内容之后再进行回复。 可以用微信里自带的语音转文本或者openai的whisper。

目前dll不支持语音消息，很遗憾

**Comment by jisongkun** [comment]
可否添加自定义openai地址的字段。自己做了openai api国内能访问的反向代理，要不然整个机子要翻墙来访问openai，还得处理微信分流。

**Comment by kamike** [comment]
> > -i生成的图片希望可以有地方配置张数，现在生成的图片好像最低4张，有时候出现8张。希望可以自己定义最大图片数量
> 
> 每一次都是4张


这个调用SD的模型是固定返回四张吗？有没有办法传参数过去只给一张？
另外画图只支持英文的问题，完全可以用GPT先翻译一次，再画图

**Comment by SnapdragonLee** [comment]
> > > -i生成的图片希望可以有地方配置张数，现在生成的图片好像最低4张，有时候出现8张。希望可以自己定义最大图片数量
> > 
> > 
> > 每一次都是4张
> 
> 这个调用SD的模型是固定返回四张吗？有没有办法传参数过去只给一张？ 另外画图只支持英文的问题，完全可以用GPT先翻译一次，再画图

没有问题的 但是目前没有时间维护 很抱歉

**Comment by ahui9605** [comment]
> > 请问可以增加微信语音消息的文字转换功能吗？ 比如，我发送给 ChatGPT 一个语音消息，然后 ChatGPT 自动将其转换为文字，知道我说了什么内容之后再进行回复。 可以用微信里自带的语音转文本或者openai的whisper。
> 
> 目前dll不支持语音消息，很遗憾

好吧， 谢谢

**Comment by SnapdragonLee** [comment]
新版本的功能需求可以进入这个[issue](#90)里面继续提，现在作者有信心和时间自己写hook工具链和新的架构了
