### ISSUE TITLE
Stable Diffusion AI bug

### ISSUE THREAD

**Issue by joe12801** [SnapdragonLee/ChatGPT-weBot#55]
怎么使用 Stable Diffusion AI  对微信，在微信输入 -i +内容，没什么反应

**Comment by SnapdragonLee** [comment]
看看函数调用栈，或者报错信息

**Comment by joe12801** [comment]
> 看看函数调用栈，或者报错信息

有没有使用案例，正常的聊天可以用，Stable Diffusion这个功能没什么用，没反应

**Comment by SnapdragonLee** [comment]
服务器压力太大了，目前我得改一下结构才能多次请求，等一下修复吧

**Comment by free-y** [comment]
用这个prompt： a happy googler
直接输出
Stable Diffusion V2.1 arts are done!
但是不输出图片

**Comment by SnapdragonLee** [comment]
是的，压力很大，没需改之前 可能需要手动多输入几次

**Comment by free-y** [comment]
哈哈哈，多试了几次可以出来，但是最好不要画人，惨不忍睹

**Comment by SnapdragonLee** [comment]
是的，这是恐怖谷效应，通用的V2.1是这样的

**Comment by free-y** [comment]
> 是的，这是恐怖谷效应，通用的V2.1是这样的

谢谢大佬，正常画风的要怎么弄呢？

**Comment by lious68** [comment]
作者的有stable diff 有提供api的镜像没，是否能提供出来？
config 里提供调用接口配置。
这样，大家用sd的时候可以调私有的画图。

**Comment by SnapdragonLee** [comment]
还是这个问题，我的电脑无法都用sd，所以没法帮助大家

**Comment by SnapdragonLee** [comment]
新的版本我想增加可以使用自定义端口的本地服务，如果兄弟们还有兴趣可以来讨论一下具体细节，因为本人没有sd环境
QQ群：815929945
