### ISSUE TITLE
无法接受信息

### ISSUE THREAD

**Issue by dvdcjw** [SnapdragonLee/ChatGPT-weBot#56]
我把on_open的    ws.send(send_txt_msg("server is online " + str(time.ctime()), "filehelper")) 取消注释后，启动时给文件传输助手发送信息。
但是用小号给电脑上的号私聊的时候一直没有回复，我把其中的print(j)取消注释之后发现除了服务器的heart beat之外无法接受任何信息，不管是图片还是文字，就更不可能调用handle_recv_txt_msg了

**Comment by dvdcjw** [comment]
![image](https://user-images.githubusercontent.com/97785943/227753362-e57d5315-8402-4617-a933-bd5851ea5914.png)

**Comment by dvdcjw** [comment]
> 

这个右键管理员之后解决了
现在收到消息没有反应，只有初始时输出自身微信号

**Comment by dvdcjw** [comment]
这对python版本有要求吗？我用的3.9

**Comment by SnapdragonLee** [comment]
我没有明白为什么还有heartbeat包，用的是什么版本的代码

**Comment by Ssss55** [comment]
同样遇到此问题，注入dll的方式可以收到信息，funtool的方法是收不到消息的

**Comment by SnapdragonLee** [comment]
我认为可能是有占用，新版本的已经不需要funtool，而是用自建SDK，欢迎期待
如果还有问题，欢迎重新开启本issue
