### ISSUE TITLE
联网以后报错

### ISSUE THREAD

**Issue by free-y** [SnapdragonLee/ChatGPT-weBot#58]
错误信息

ConnectionError: ddg-webapp API Error (code: -2)

**Comment by SnapdragonLee** [comment]
这个应该是代理问题吧，之前我记得我遇过这个error

**Comment by free-y** [comment]
> 这个应该是代理问题吧，之前我记得我遇过这个error

之前可以的，刚才试了一下突然不行了

**Comment by SnapdragonLee** [comment]
我这里显示还是正常的

**Comment by free-y** [comment]
> 我这里显示还是正常的

我知道了，因为联网这边的请求没有走proxy? 我这边是配的proxy翻墙

**Comment by SnapdragonLee** [comment]
是的，有可能是的
