### ISSUE TITLE
-o,-i 的问题

### ISSUE THREAD

**Issue by ZSTank** [SnapdragonLee/ChatGPT-weBot#59]
这两个指令没有任何反应啊，既没有报错，也没有任何的返回，求问大佬，要怎么解决？是不是我哪里没设置好，还是这个功能还没好？

**Comment by SnapdragonLee** [comment]
弄好了的，注意看详细的配置指引

**Comment by ZSTank** [comment]
> 弄好了的，注意看详细的配置指引，在Readme中有 -i指令目前有一些bug，可能需要多试试才可以进行画图

我尝试了一下，果然是大佬说的，多试几次就好

**Comment by dvdco** [comment]
> 请问是使用的微信个人号吗？ 会否容易被微信封号？

不放心可以sms-activate.org买一个俄罗斯的手机号，四块钱以内就能注册微信小号。
