### ISSUE TITLE
我用的clash全局代理，现在报错提示

### ISSUE THREAD

**Issue by dengliyan** [SnapdragonLee/ChatGPT-weBot#60]
api_config.json中的proxy为空

现在报错信息如下
raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='openaipublic.blob.core
.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.
tiktoken (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

请问需要怎么配置

**Comment by SnapdragonLee** [comment]
去clash查看自己的规则文件，如果没有代理openai请加入代理规则，具体做法是：
- DOMAIN-SUFFIX,openai.com, {你的代理规则}

**Comment by Toifyx** [comment]
> 去clash查看自己的规则文件，如果没有代理openai请加入代理规则，具体做法是：
> 
> * DOMAIN-SUFFIX,openai.com, {你的代理规则}

请问一下 .config/api_config.json      有一个proxy节点的配置，这个配置没有样例。

如何配置呢？以下是环境变量的配置
https_proxy=http://127.0.0.1:7890
http_proxy=http://127.0.0.1:7890
all_proxy=socks5://127.0.0.1:7890

**Comment by SnapdragonLee** [comment]
这个我不建议设置，因为我也没使用过hh，这部分没法帮助到你qwq

**Comment by SnapdragonLee** [comment]
如果还是有问题可以重新开帖子进行回复
