### ISSUE TITLE
funtool 会突然断开，并且整个文件被删除。

### ISSUE THREAD

**Issue by ZSTank** [SnapdragonLee/ChatGPT-weBot#61]
我正常运行的过程中，突然报错：[WinError 10054] 远程主机强迫关闭了一个现有的连接。
然后我就发现了funtool消失了，不仅仅是被强制关闭，而是直接被删除，我在任何文件夹都找不到。

请问大佬，这个为什么会产生？如果用dll会不会好点，哪一个封号的风险低？

另外，请问是否有试过最多同时能回复几个对话的用户？我有一次五六个人在用的时候，会卡住没有任何回复。
万分感谢大佬~

**Comment by dvdco** [comment]
多人访问的问题，我认为应该可以修改wxclient.py 中 211 到 220 中range的后参数，这应该会增加处理聊天的线程，但是我建议你先把源代码注释保存因为更改线程数量可能带来难以预料的后果

**Comment by SnapdragonLee** [comment]
@dvdco 线程多其实可以的，但是我怕openai在后面搞怪，有的时候多个请求并发可以拿到结果，有的时候则不行，所以这个问题比较麻烦，因为错误没法稳定触发
