### ISSUE TITLE
ConnectionError: ChatGPT API error HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000000005459BB0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。')) (code: -3)

### ISSUE THREAD

**Issue by linuxxx** [SnapdragonLee/ChatGPT-weBot#63]
ConnectionError: ChatGPT API error HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000000005459BB0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。')) (code: -3)

**Comment by dvdco** [comment]
小墙墙，挂梯子

**Comment by jk256** [comment]
这443明细是网络问题啊 ，你梯子没弄好吧

**Comment by SnapdragonLee** [comment]
梯子全局代理

**Comment by nebulau** [comment]
梯子有了是不是要填proxy字段啊，这个咋填

**Comment by dvdco** [comment]
> 梯子有了是不是要填proxy字段啊，这个咋填

天底下梯子多了，先挂个名字

**Comment by nebulau** [comment]
> > 梯子有了是不是要填proxy字段啊，这个咋填
> 
> 天底下梯子多了，先挂个名字

请问怎么挂名字啊，梯子开了，api_config.json中的proxy字段要填啥呢

**Comment by dvdco** [comment]
你如果用外置梯子全局代理就不需要填写这个局部代理了

**Comment by nebulau** [comment]
> 你如果用外置梯子全局代理就不需要填写这个局部代理了

谢谢

**Comment by SnapdragonLee** [comment]
有问题可重新打开这个issue
