### ISSUE TITLE
运行main.py后报错，路径不对吗？

### ISSUE THREAD

**Issue by jk256** [SnapdragonLee/ChatGPT-weBot#65]
![123](https://user-images.githubusercontent.com/31434934/229287665-a0e3c3aa-09b8-4cef-8171-a27a26e9f245.png)

**Comment by SnapdragonLee** [comment]
错误，根据你的调用栈，是 `api_config.json` 文件的设置不符合json语法

**Comment by jk256** [comment]
> 语法

好的谢谢我外检查下

**Comment by jk256** [comment]
> 错误，根据你的调用栈，是`api_config.json`文件的设置不符json语法

已测试通过，感谢你的热情，请注意接收奶茶钱

**Comment by SnapdragonLee** [comment]
@jk256 hhh，谢谢投喂
