### ISSUE TITLE
跑不起来，能不能麻烦看下这是啥情况啊？

### ISSUE THREAD

**Issue by rover1003** [SnapdragonLee/ChatGPT-weBot#66]
<websocket._app.WebSocketApp object at 0x0000021E753C2B10>
[WinError 10061] 由于目标计算机积极拒绝，无法连接。
<websocket._app.WebSocketApp object at 0x0000021E753C2B10>
closed

**Comment by SnapdragonLee** [comment]
没有注入成功导致的，重新注入或重新打开funtools

**Comment by rover1003** [comment]
嗯，换了funtools可以了。前面用的是dll注入。

**Comment by Ethan-Ming** [comment]
@rover1003 我也遇到同样无法注入成功问题，能说说是怎么换funtools的吗

**Comment by Delppine1024** [comment]
> @rover1003 我也遇到同样无法注入成功问题，能说说是怎么换funtools的吗

这个根本不是换funtools的问题了，现在改方式了，直接用新的注入工具就行
