### ISSUE TITLE
"engine": "gpt-3.5-turbo", 其它模型不支持么

### ISSUE THREAD

**Issue by likohank** [SnapdragonLee/ChatGPT-weBot#67]
engine 对应的值需要为其中之一：gpt-3.5-turbo, gpt-3.5-turbo-0301, gpt-4, gpt-4-0314, gpt-4-32k, gpt-4-32k-0314。

返回内容为 {'error': {'message': 'The model: `gpt-4` does not exist', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}

**Comment by SnapdragonLee** [comment]
您需要申请到gpt-4的使用资格才可以使用的
