### ISSUE TITLE
偶尔reply回复消息不全

### ISSUE THREAD

**Issue by jk256** [SnapdragonLee/ChatGPT-weBot#71]
如图，没有超过maxtoken，是和 #29 一个问题吗
![1111111111111111](https://user-images.githubusercontent.com/31434934/229698479-86b710e0-f78e-414b-ac76-b8965d0cbef9.png)
![Uploading 2222222222222.png…]()

**Comment by SnapdragonLee** [comment]
这是因为单词对话上限token是max_token，这个token里面包含了之前的问题和回答，所以每次回答最多可以接受到max_token，所以会截断
