### ISSUE TITLE
install requirements文件时错误，Windows Embedded Standard 7

### ISSUE THREAD

**Issue by jk256** [SnapdragonLee/ChatGPT-weBot#72]
![image](https://user-images.githubusercontent.com/31434934/231491422-439ed939-63d8-4be1-8f24-3f733918c7d3.jpeg)

如图，嵌入式win7设备最后一步安装时卡在toktoken安装失败。提示缺少一个whl？按照error提示没有在网上找到相同解决方案。使用的是全新安装的python3.8.10。也已经pip install --upgrade 。是否是因为此版本win7过于精简的原因？是否有人遇到过类似问题

**Comment by SnapdragonLee** [comment]
可以选择试试直接下载whl，然后手动安装

**Comment by jk256** [comment]
已解决。手动安装依旧报错，懒得折腾了。此机器来看tiktoken的whl安装 对win32不友好，换了64位一遍过

**Comment by SnapdragonLee** [comment]
ok
