### ISSUE TITLE
在群里面别人@它无法识别，这个是最大的问题

### ISSUE THREAD

**Issue by kamike** [SnapdragonLee/ChatGPT-weBot#74]
通过hook微信pc端，目前看来是最不容易被封的一种方式，这是我选这个库的原因。
用下来感觉最大的问题就是在群里面别人@它无法识别，如果这是hook库的问题，看看能不能直接配置一个昵称，匹配上就识别出来。
这样好过完全没用的好，在群不能艾特，这群聊功能没有意义了

**Comment by SnapdragonLee** [comment]
这个功能可以做到的，指定昵称，甚至可以指定群聊，但目前还是希望dll可以支持@我

**Comment by kamike** [comment]
可以给一下这个dll的项目吗，关注下

**Comment by SnapdragonLee** [comment]
这个目前可以做到了，新版的SDK改好以后自带这个功能，欢迎期待
这个issue暂时关闭
