### ISSUE TITLE
是否支持第三方反代的openai key的使用

### ISSUE THREAD

**Issue by jk256** [SnapdragonLee/ChatGPT-weBot#75]
如图，是否可以将api地址迁移到第三方反代提供商
![111111111111](https://user-images.githubusercontent.com/31434934/233784028-2cb3e5e5-26a9-408f-8d9c-7091dd99eff7.png)
既不用走proxy

**Comment by jk256** [comment]
看了接口文档，基本一致，换下地址就可以了应该，我先试下

**Comment by kamike** [comment]
自己改一下python脚本里面api访问的地址就行了，很简单

**Comment by SnapdragonLee** [comment]
可以的，api接口只要返回的消息相同，就可任意更换后端地址

**Comment by SnapdragonLee** [comment]
有问题请重新开issue
