### ISSUE TITLE
-o 的功能好像挂了~

### ISSUE THREAD

**Issue by MrKingSz** [SnapdragonLee/ChatGPT-weBot#78]
错误提示
ConnectionError: Cannot access internet info (code: 404)

**Comment by SnapdragonLee** [comment]
抱歉最近事情很多，暂时没有时间维护qwq

大约2周只能会进行维护

**Comment by SnapdragonLee** [comment]
抱歉一直在忙毕业和升学的事情，没有来得及维护~
如果依然还有问题请移步到 #90 ，进行更新请求。
目前没有更新的回复，如果有新问题请重新打开本issue进行提问，谢谢！
