### ISSUE TITLE
1.02版本安装出错

### ISSUE THREAD

**Issue by safir98** [SnapdragonLee/ChatGPT-weBot#83]
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from client.wxclient import ws
  File "F:\2023\9、chatWxBot_safir\weBot\weBot1.02\client\wxclient.py", line 6, in <module>
    from basic.task import *
  File "F:\2023\9、chatWxBot_safir\weBot\weBot1.02\basic\task.py", line 11, in <module>
    from apibase.ChatGPTAPI import ChatbotError
  File "F:\2023\9、chatWxBot_safir\weBot\weBot1.02\apibase\ChatGPTAPI.py", line 3, in <module>
    import tiktoken
ModuleNotFoundError: No module named 'tiktoken'

pip install tiktoken

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))': /simple/tiktoken/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))': /simple/tiktoken/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))': /simple/tiktoken/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))': /simple/tiktoken/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))': /simple/tiktoken/
Could not fetch URL https://pypi.org/simple/tiktoken/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/tiktoken/ (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))) - skipping
ERROR: Could not find a version that satisfies the requirement tiktoken (from versions: none)
ERROR: No matching distribution found for tiktoken

**Comment by SnapdragonLee** [comment]
新版需要重新pip install -r requirements.txt

**Comment by SnapdragonLee** [comment]
目前没有更新的回复，如果有新问题请重新打开本issue进行提问，谢谢！
