### ISSUE TITLE
它在一本正经的胡说八道，不知道问题出在哪哈哈

### ISSUE THREAD

**Issue by Tammy20i** [SnapdragonLee/ChatGPT-weBot#84]
![微信图片_20230517140456](https://github.com/SnapdragonLee/ChatGPT-weBot/assets/133845980/4aad4544-8a42-4cb4-975c-b7919d1acfab)
问1997年（牛），它说属马

**Comment by SnapdragonLee** [comment]
这是chatgpt经典了，文学素养可以，但是数学问题一塌糊度，望周知

**Comment by SnapdragonLee** [comment]
目前没有更新的回复，如果有新问题请重新打开本issue进行提问，谢谢！
