### ISSUE TITLE
回复经常不完整，麻烦给个建议去哪里排查原因

### ISSUE THREAD

**Issue by Tammy20i** [SnapdragonLee/ChatGPT-weBot#85]
![image](https://github.com/SnapdragonLee/ChatGPT-weBot/assets/133845980/a470260e-a042-4045-9b6e-27e0574b245a)
回复经常不完整，麻烦给个建议去哪里排查原因

**Comment by SnapdragonLee** [comment]
单一的对话token有限制，注意仔细阅读文档，要经常总结
要不然每一次发送的对话中会抹掉前文的某一个对话的问题或回答，用来补偿token的长度

**Comment by SnapdragonLee** [comment]
目前没有更新的回复，如果有新问题请重新打开本issue进行提问，谢谢！
