### ISSUE TITLE
纯新手小白的详细解释指导

### ISSUE THREAD

**Issue by SnapdragonLee** [SnapdragonLee/ChatGPT-weBot#9]
（省流量一句话：config.json里面的两个chatkey修改后，保存保存保存--->cmd.exe要重新运行main.py，然后才能生效）

环境：旧电脑win7，python官网下载python 3.8.10, installer,32位置，默认方式安装

软件及安装包：releases中下载3.6.0.18版的微信安装包，文档最底部下载dll啥啥啥的（比我还菜鸡那也就不用琢磨这个部署方式了。

**严格按照作者的123456顺序进行，就可以正常使用了。**

容易出问题的地方（额，菜鸡本鸡遇到的情况）：

1，pip指令不生效，搜一下，有两行代码，会重装一下，然后就可以用pip开始第一步
（作者补充一句，是python安装目录下的scripts目录没有加入系统环境变量导致的，如果你安装的是anaconda/minicona，那不会有这个问题）

2，默认配置中的keyword是-c，我在聊天中用的是c，名字叫错了，所以没有应答，同样的issue我已经进行了标记 https://github.com/SnapdragonLee/ChatGPT-weBot/issues/7

3，修改-c为其他内容后，重新运行 python main.py，再在微信中聊天就没问题了

4，keyword可以修改为中文，亲测可用。

_Originally posted by @xy185 in https://github.com/SnapdragonLee/ChatGPT-weBot/issues/6#issuecomment-1442834546_

**Comment by SnapdragonLee** [comment]
注意，使用的时候请配置.config文件夹下两个配置文件，分别对应：
config.json，机器人触发指令的各种关键字，将机器人对话做成类似于命令行调用的工具
rev_config.json，对应命令行调用chatgpt API的操作，请仔细根据文档填写

**Comment by WC-wuqi** [comment]
rev_config.json文件里的  
"proxy": "",
  "email": "",
  "password": "",
  "session_token": "",
  "paid": true

端口也需要填么？有token也需要填账号密码是么？我配置了，发消息机器人也没有任何回应啊

**Comment by SnapdragonLee** [comment]
请更新到最新的版本，参照readme一步一步完成

**Comment by SnapdragonLee** [comment]
由于本教程已经过时，暂时关闭本issue
