### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by haiou2012** [SnapdragonLee/ChatGPT-weBot#94]
<img width="826" alt="dcec237cf18c4c15a28ea4be7d1d53c" src="https://github.com/SnapdragonLee/ChatGPT-weBot/assets/130887693/4b29ab2b-1b70-41c4-bbef-97b519d220c6">
问问题出现了错误（就不回答了）

**Comment by haiou2012** [comment]
画图也不行，就显示”Handshake status 503 Service Unavailable
Stable Diffusion V2.1 arts are done!“

**Comment by SnapdragonLee** [comment]
这个问题我感觉应该是你没有开全局代理导致的
注意梯子的配置里面有没有关于openai等网站的代理

**Comment by SnapdragonLee** [comment]
新版正在做，实在解决不了可以期待一下新版
